In [31]:
import pandas as pd

In [64]:
# Import the dataframe from a file or url.
df = pd.read_csv(r'C:\Users\Gerardo\Documents\Python\Python Web Scraping\Top 100 USA\Top100Companies.csv')

In [65]:
# .info() breakup of the data with columns, nulls, and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Rank                    100 non-null    int64
 1   Name                    100 non-null    object
 2   Industry                100 non-null    object
 3   Revenue (USD millions)  100 non-null    object
 4   Revenue growth          100 non-null    object
 5   Employees               100 non-null    object
 6   Headquarters            100 non-null    object
dtypes: int64(1), object(6)
memory usage: 5.6+ KB

In [66]:
# .shape describes hoe many rows and columns (r,c)
df.shape

(100, 7)

In [67]:
# .head() gives a look up of the first values of the df
df.head(5)

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"

In [68]:
# Change values to have a look of the 100 columns of the data frame
pd.set_option('display.max.rows', 100)

In [69]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
10,11,AmerisourceBergen,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
11,12,Costco,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
12,13,Microsoft,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
14,15,Cigna,Health Insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
15,16,Marathon Petroleum,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
16,17,Phillips 66,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
17,18,Valero Energy,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
18,19,Ford Motor Company,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
19,20,The Home Depot,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
20,21,General Motors,Automotive,"156,735",23.4%,"167,000","Detroit, Michigan"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,"154,792",21.7%,"293,723","New York City, New York"
23,24,Kroger,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
27,28,Fannie Mae,Financials,"121,596",19.7%,"8,000","Washington, D.C."
28,29,Comcast,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate,"120,741",28.5%,"160,700","Dallas, Texas"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
31,32,Bank of America,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
32,33,Target Corporation,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
34,35,Archer Daniels Midland,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
35,36,Citigroup,Financials,"101,078",26.6%,"238,104","New York City, New York"
36,37,United Parcel Service,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
38,39,Lowe's,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
40,41,FedEx,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
41,42,Humana,Health Insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
43,44,State Farm,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
44,45,Freddie Mac,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
45,46,PepsiCo,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
46,47,Wells Fargo,Financials,"82,859",0.5%,"238,000","San Francisco, California"
47,48,The Walt Disney Company,Media,"82,722",22.7%,"195,800","Burbank, California"
48,49,ConocoPhillips,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
49,50,Tesla,Automotive and Energy,"81,462",51.4%,"127,855","Austin, Texas"
50,51,Procter & Gamble,Consumer products Manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
52,53,Albertsons,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
53,54,General Electric,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
54,55,MetLife,Financials,"69,898",1.7%,"45,000","New York City, New York"
55,56,Goldman Sachs,Financials,"68,711",5.7%,"48,500","New York City, New York"
56,57,Sysco,Food Service,"68,636",33.8%,"70,510","Houston, Texas"
57,58,Bunge Limited,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
58,59,RTX Corporation,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,"66,608",6.9%,"156,000","Chicago, Illinois"
60,61,StoneX Group,Financials,"66,036",55.3%,305,"New York City, New York"
61,62,Lockheed Martin,Aerospace and Defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
62,63,Morgan Stanley,Financials,"65,936",7.9%,"82,427","New York City, New York"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
65,66,TD Synnex,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
66,67,IBM,Technology,"60,530",16.3%,"303,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
68,69,Prudential Financial,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
69,70,Caterpillar,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
71,72,World Fuel Services,Petroleum industry and Logistics,"59,043",88.4%,"5,214","Miami, Florida"
72,73,New York Life Insurance Company,Insurance,"58,445",14.2%,"15,050","New York City, New York"
73,74,Enterprise Products,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
74,75,AbbVie,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
75,76,Plains All American Pipeline,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
76,77,Dow Chemical Company,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
77,78,AIG,Insurance,"56,437",8.4%,"26,200","New York City, New York"
78,79,American Express,Financial,"55,625",27.3%,"77,300","New York City, New York"
79,80,Publix,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
80,81,Charter Communications,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
81,82,Tyson Foods,Food Processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
83,84,Cisco,Telecom Hardware Manufacturing,"51,557",3.5%,"83,300","San Jose, California"
84,85,Nationwide Mutual Insurance Company,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
85,86,Allstate,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
87,88,Liberty Mutual,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
88,89,TJX,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
90,91,American Airlines,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
91,92,CHS,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
92,93,Performance Food Group,Food Processing,"47,194",61.6%,"34,825","Richmond, Virginia"
93,94,PBF Energy,Petroleum industry,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
94,95,Nike,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [70]:
# Filter a single column
df['Name']

0                                 Walmart
1                                  Amazon
2                             Exxon Mobil
3                                   Apple
4                      UnitedHealth Group
5                              CVS Health
6                      Berkshire Hathaway
7                                Alphabet
8                    McKesson Corporation
9                     Chevron Corporation
10                      AmerisourceBergen
11                                 Costco
12                              Microsoft
13                        Cardinal Health
14                                  Cigna
15                     Marathon Petroleum
16                            Phillips 66
17                          Valero Energy
18                     Ford Motor Company
19                         The Home Depot
20                         General Motors
21                        Elevance Health
22                         JPMorgan Chase
23                                 Kroger
24                                Centene
25                 Verizon Communications
26               Walgreens Boots Alliance
27                             Fannie Mae
28                                Comcast
29                                   AT&T
30                         Meta Platforms
31                        Bank of America
32                     Target Corporation
33                      Dell Technologies
34                 Archer Daniels Midland
35                              Citigroup
36                  United Parcel Service
37                                 Pfizer
38                                 Lowe's
39                      Johnson & Johnson
40                                  FedEx
41                                 Humana
42               Energy Transfer Partners
43                             State Farm
44                            Freddie Mac
45                                PepsiCo
46                            Wells Fargo
47                The Walt Disney Company
48                         ConocoPhillips
49                                  Tesla
50                       Procter & Gamble
51           United States Postal Service
52                             Albertsons
53                       General Electric
54                                MetLife
55                          Goldman Sachs
56                                  Sysco
57                          Bunge Limited
58                        RTX Corporation
59                                 Boeing
60                           StoneX Group
61                        Lockheed Martin
62                         Morgan Stanley
63                                  Intel
64                                     HP
65                              TD Synnex
66                                    IBM
67                         HCA Healthcare
68                   Prudential Financial
69                            Caterpillar
70                            Merck & Co.
71                    World Fuel Services
72        New York Life Insurance Company
73                    Enterprise Products
74                                 AbbVie
75           Plains All American Pipeline
76                   Dow Chemical Company
77                                    AIG
78                       American Express
79                                 Publix
80                 Charter Communications
81                            Tyson Foods
82                             John Deere
83                                  Cisco
84    Nationwide Mutual Insurance Company
85                               Allstate
86                        Delta Air Lines
87                         Liberty Mutual
88                                    TJX
89                Progressive Corporation
90                      American Airlines
91                                    CHS
92                 Performance Food Group
93                             PBF Energy
94                                   Nike
95                               Best Buy
96                   Bristol-Myers Squibb
97                        United Airlines
98               Thermo Fisher Scientific
99                               Qualcomm
Name: Name, dtype: object

In [71]:
# Filter many columns
df[['Name', 'Industry', 'Employees']]

,Name,Industry,Employees
0,Walmart,Retail,"2,100,000"
1,Amazon,Retail and Cloud Computing,"1,540,000"
2,Exxon Mobil,Petroleum industry,"62,000"
3,Apple,Electronics industry,"164,000"
4,UnitedHealth Group,Healthcare,"400,000"
5,CVS Health,Healthcare,"259,500"
6,Berkshire Hathaway,Conglomerate,"383,000"
7,Alphabet,Technology,"156,000"
8,McKesson Corporation,Health,"48,500"
9,Chevron Corporation,Petroleum industry,"43,846"
10,AmerisourceBergen,Pharmaceutical industry,"41,500"
11,Costco,Retail,"304,000"
12,Microsoft,Technology,"221,000"
13,Cardinal Health,Healthcare,"46,035"
14,Cigna,Health Insurance,"70,231"
15,Marathon Petroleum,Petroleum industry,"17,800"
16,Phillips 66,Petroleum industry,"13,000"
17,Valero Energy,Petroleum industry,"9,743"
18,Ford Motor Company,Automotive industry,"173,000"
19,The Home Depot,Retail,"471,600"
20,General Motors,Automotive,"167,000"
21,Elevance Health,Healthcare,"102,200"
22,JPMorgan Chase,Financial services,"293,723"
23,Kroger,Retail,"430,000"
24,Centene,Healthcare,"74,300"
25,Verizon Communications,Telecommunications,"117,100"
26,Walgreens Boots Alliance,Pharmaceutical industry,"262,500"
27,Fannie Mae,Financials,"8,000"
28,Comcast,Telecommunications,"186,000"
29,AT&T,Conglomerate,"160,700"
30,Meta Platforms,Technology,"86,482"
31,Bank of America,Financials,"216,823"
32,Target Corporation,Retail,"440,000"
33,Dell Technologies,Technology,"133,000"
34,Archer Daniels Midland,Food industry,"41,181"
35,Citigroup,Financials,"238,104"
36,United Parcel Service,Transportation,"404,700"
37,Pfizer,Pharmaceutical industry,"83,000"
38,Lowe's,Retail,"244,500"
39,Johnson & Johnson,Pharmaceutical industry,"152,700"
40,FedEx,Transportation,"518,249"
41,Humana,Health Insurance,"67,100"
42,Energy Transfer Partners,Petroleum industry,"12,565"
43,State Farm,Financials,"60,519"
44,Freddie Mac,Financials,"7,819"
45,PepsiCo,Beverage,"315,000"
46,Wells Fargo,Financials,"238,000"
47,The Walt Disney Company,Media,"195,800"
48,ConocoPhillips,Petroleum industry,"9,500"
49,Tesla,Automotive and Energy,"127,855"
50,Procter & Gamble,Consumer products Manufacturing,"106,000"
51,United States Postal Service,Logistics,"576,000"
52,Albertsons,Retail,"198,650"
53,General Electric,Conglomerate,"172,000"
54,MetLife,Financials,"45,000"
55,Goldman Sachs,Financials,"48,500"
56,Sysco,Food Service,"70,510"
57,Bunge Limited,Food industry,"23,000"
58,RTX Corporation,Conglomerate,"182,000"
59,Boeing,Aerospace and defense,"156,000"
60,StoneX Group,Financials,305
61,Lockheed Martin,Aerospace and Defense,"116,000"
62,Morgan Stanley,Financials,"82,427"
63,Intel,Technology,"131,900"
64,HP,Technology,"58,000"
65,TD Synnex,Infotech,"28,500"
66,IBM,Technology,"303,100"
67,HCA Healthcare,Healthcare,"250,500"
68,Prudential Financial,Financials,"39,583"
69,Caterpillar,Machinery,"109,100"
70,Merck & Co.,Pharmaceutical industry,"68,000"
71,World Fuel Services,Petroleum industry and Logistics,"5,214"
72,New York Life Insurance Company,Insurance,"15,050"
73,Enterprise Products,Petroleum industry,"7,300"
74,AbbVie,Pharmaceutical industry,"50,000"
75,Plains All American Pipeline,Petroleum industry,"4,100"
76,Dow Chemical Company,Chemical industry,"37,800"
77,AIG,Insurance,"26,200"
78,American Express,Financial,"77,300"
79,Publix,Retail,"242,000"
80,Charter Communications,Telecommunications,"101,700"
81,Tyson Foods,Food Processing,"142,000"
82,John Deere,Agriculture manufacturing,"82,239"
83,Cisco,Telecom Hardware Manufacturing,"83,300"
84,Nationwide Mutual Insurance Company,Financial,"24,791"
85,Allstate,Insurance,"54,250"
86,Delta Air Lines,Airline,"95,000"
87,Liberty Mutual,Insurance,"50,000"
88,TJX,Retail,"329,000"
89,Progressive Corporation,Insurance,"55,063"
90,American Airlines,Airline,"129,700"
91,CHS,Agriculture cooperative,"10,014"
92,Performance Food Group,Food Processing,"34,825"
93,PBF Energy,Petroleum industry,"3,616"
94,Nike,Apparel,"79,100"
95,Best Buy,Retail,"71,100"
96,Bristol-Myers Squibb,Pharmaceutical industry,"34,300"
97,United Airlines,Airline,"92,795"
98,Thermo Fisher Scientific,Laboratory instruments,"130,000"
99,Qualcomm,Technology,"51,000"

In [72]:
# Filter columns with operators and change dtypes 
df['Employees'] = df['Employees'].str.replace(',','')
df['Revenue (USD millions)'] = df['Revenue (USD millions)'].str.replace(',','')
df = df.astype({'Revenue (USD millions)':'int','Employees':'int'})
df[df['Employees']>50000]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,611289,6.7%,2100000,"Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,513983,9.4%,1540000,"Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,413680,44.8%,62000,"Spring, Texas"
3,4,Apple,Electronics industry,394328,7.8%,164000,"Cupertino, California"
4,5,UnitedHealth Group,Healthcare,324162,12.7%,400000,"Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,322467,10.4%,259500,"Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,302089,9.4%,383000,"Omaha, Nebraska"
7,8,Alphabet,Technology,282836,9.8%,156000,"Mountain View, California"
11,12,Costco,Retail,226954,15.8%,304000,"Issaquah, Washington"
12,13,Microsoft,Technology,198270,18.0%,221000,"Redmond, Washington"
14,15,Cigna,Health Insurance,180516,3.7%,70231,"Bloomfield, Connecticut"
18,19,Ford Motor Company,Automotive industry,158057,15.9%,173000,"Dearborn, Michigan"
19,20,The Home Depot,Retail,157403,4.1%,471600,"Atlanta, Georgia"
20,21,General Motors,Automotive,156735,23.4%,167000,"Detroit, Michigan"
21,22,Elevance Health,Healthcare,156595,13.0%,102200,"Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,154792,21.7%,293723,"New York City, New York"
23,24,Kroger,Retail,148258,7.5%,430000,"Cincinnati, Ohio"
24,25,Centene,Healthcare,144547,14.7%,74300,"St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,136835,2.4%,117100,"New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,132703,10.7%,262500,"Deerfield, Illinois"
28,29,Comcast,Telecommunications,121427,4.3%,186000,"Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate,120741,28.5%,160700,"Dallas, Texas"
30,31,Meta Platforms,Technology,116609,1.1%,86482,"Menlo Park, California"
31,32,Bank of America,Financials,115053,22.6%,216823,"Charlotte, North Carolina"
32,33,Target Corporation,Retail,109120,2.9%,440000,"Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,102301,4.4%,133000,"Round Rock, Texas"
35,36,Citigroup,Financials,101078,26.6%,238104,"New York City, New York"
36,37,United Parcel Service,Transportation,100338,3.1%,404700,"Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,100330,23.4%,83000,"New York City, New York"
38,39,Lowe's,Retail,97059,0.8%,244500,"Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,94943,1.2%,152700,"New Brunswick, New Jersey"
40,41,FedEx,Transportation,93512,11.4%,518249,"Memphis, Tennessee"
41,42,Humana,Health Insurance,92870,11.8%,67100,"Louisville, Kentucky"
43,44,State Farm,Financials,89328,8.6%,60519,"Bloomington, Illinois"
45,46,PepsiCo,Beverage,86859,8.7%,315000,"Purchase, New York"
46,47,Wells Fargo,Financials,82859,0.5%,238000,"San Francisco, California"
47,48,The Walt Disney Company,Media,82722,22.7%,195800,"Burbank, California"
49,50,Tesla,Automotive and Energy,81462,51.4%,127855,"Austin, Texas"
50,51,Procter & Gamble,Consumer products Manufacturing,80187,5.3%,106000,"Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,78620,2.0%,576000,"Washington, D.C."
52,53,Albertsons,Retail,77650,8.0%,198650,"Boise, Idaho"
53,54,General Electric,Conglomerate,76555,3.2%,172000,"Boston, Massachusetts"
56,57,Sysco,Food Service,68636,33.8%,70510,"Houston, Texas"
58,59,RTX Corporation,Conglomerate,67074,4.2%,182000,"Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,66608,6.9%,156000,"Chicago, Illinois"
61,62,Lockheed Martin,Aerospace and Defense,65984,1.6%,116000,"Bethesda, Maryland"
62,63,Morgan Stanley,Financials,65936,7.9%,82427,"New York City, New York"
63,64,Intel,Technology,63054,20.1%,131900,"Santa Clara, California"
64,65,HP,Technology,62983,0.8%,58000,"Palo Alto, California"
66,67,IBM,Technology,60530,16.3%,303100,"Armonk, New York"
67,68,HCA Healthcare,Healthcare,60233,2.5%,250500,"Nashville, Tennessee"
69,70,Caterpillar,Machinery,59427,16.6%,109100,"Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,59283,15.8%,68000,"Kenilworth, New Jersey"
78,79,American Express,Financial,55625,27.3%,77300,"New York City, New York"
79,80,Publix,Retail,54942,13.5%,242000,"Lakeland, Florida"
80,81,Charter Communications,Telecommunications,54022,4.5%,101700,"Stamford, Connecticut"
81,82,Tyson Foods,Food Processing,53282,13.2%,142000,"Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,52577,19.4%,82239,"Moline, Illinois"
83,84,Cisco,Telecom Hardware Manufacturing,51557,3.5%,83300,"San Jose, California"
85,86,Allstate,Insurance,51412,3.4%,54250,"Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,50582,69.2%,95000,"Atlanta, Georgia"
88,89,TJX,Retail,49936,2.9%,329000,"Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,49611,4.0%,55063,"Mayfield Village, Ohio"
90,91,American Airlines,Airline,48971,63.9%,129700,"Fort Worth, Texas"
94,95,Nike,Apparel,46710,4.9%,79100,"Beaverton, Oregon"
95,96,Best Buy,Retail,46298,10.6%,71100,"Richfield, Minnesota"
97,98,United Airlines,Airline,44955,82.5%,92795,"Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,44915,14.5%,130000,"Waltham, Massachusetts"
99,100,Qualcomm,Technology,44200,31.7%,51000,"San Diego, California"

In [73]:
# Filter more than 1 column with operators
df[(df['Employees']>50000) & (df['Revenue (USD millions)'] >300000)]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,611289,6.7%,2100000,"Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,513983,9.4%,1540000,"Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,413680,44.8%,62000,"Spring, Texas"
3,4,Apple,Electronics industry,394328,7.8%,164000,"Cupertino, California"
4,5,UnitedHealth Group,Healthcare,324162,12.7%,400000,"Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,322467,10.4%,259500,"Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,302089,9.4%,383000,"Omaha, Nebraska"

In [74]:
# Use of .isin() works like an IN SQL clause select a column an the records you want
specific_companies = ['Walmart','Amazon','Apple','Microsoft','Chevron Corporation','Costco','PBF Energy','Tesla']
df[df['Name'].isin(specific_companies)]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,611289,6.7%,2100000,"Bentonville, Arkansas"
1,2,Amazon,Retail and Cloud Computing,513983,9.4%,1540000,"Seattle, Washington"
3,4,Apple,Electronics industry,394328,7.8%,164000,"Cupertino, California"
9,10,Chevron Corporation,Petroleum industry,246252,51.6%,43846,"San Ramon, California"
11,12,Costco,Retail,226954,15.8%,304000,"Issaquah, Washington"
12,13,Microsoft,Technology,198270,18.0%,221000,"Redmond, Washington"
49,50,Tesla,Automotive and Energy,81462,51.4%,127855,"Austin, Texas"
93,94,PBF Energy,Petroleum industry,46830,71.8%,3616,"Parsippany–Troy Hills, New Jersey"

In [75]:
# Use of contain() works like a LIKE clause from SQL works with str
df[df['Name'].str.contains('on')]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
1,2,Amazon,Retail and Cloud Computing,513983,9.4%,1540000,"Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,413680,44.8%,62000,"Spring, Texas"
8,9,McKesson Corporation,Health,276711,4.8%,48500,"Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,246252,51.6%,43846,"San Ramon, California"
15,16,Marathon Petroleum,Petroleum industry,180012,27.6%,17800,"Findlay, Ohio"
25,26,Verizon Communications,Telecommunications,136835,2.4%,117100,"New York City, New York"
32,33,Target Corporation,Retail,109120,2.9%,440000,"Minneapolis, Minnesota"
39,40,Johnson & Johnson,Pharmaceutical industry,94943,1.2%,152700,"New Brunswick, New Jersey"
48,49,ConocoPhillips,Petroleum industry,82156,69.9%,9500,"Houston, Texas"
52,53,Albertsons,Retail,77650,8.0%,198650,"Boise, Idaho"
58,59,RTX Corporation,Conglomerate,67074,4.2%,182000,"Arlington County, Virginia"
60,61,StoneX Group,Financials,66036,55.3%,305,"New York City, New York"
80,81,Charter Communications,Telecommunications,54022,4.5%,101700,"Stamford, Connecticut"
81,82,Tyson Foods,Food Processing,53282,13.2%,142000,"Springdale, Arkansas"
84,85,Nationwide Mutual Insurance Company,Financial,51450,8.6%,24791,"Columbus, Ohio"
89,90,Progressive Corporation,Insurance,49611,4.0%,55063,"Mayfield Village, Ohio"

In [76]:
# Filter by index with filter loc iloc
# Set an index with .set_index()
df2 = df.set_index('Name')
# Filter from the index with filter() function
df2.filter(items = ['Industry','Employees'])

,Industry,Employees
Name,,
Walmart,Retail,2100000
Amazon,Retail and Cloud Computing,1540000
Exxon Mobil,Petroleum industry,62000
Apple,Electronics industry,164000
UnitedHealth Group,Healthcare,400000
CVS Health,Healthcare,259500
Berkshire Hathaway,Conglomerate,383000
Alphabet,Technology,156000
McKesson Corporation,Health,48500
Chevron Corporation,Petroleum industry,43846
AmerisourceBergen,Pharmaceutical industry,41500
Costco,Retail,304000
Microsoft,Technology,221000
Cardinal Health,Healthcare,46035
Cigna,Health Insurance,70231
Marathon Petroleum,Petroleum industry,17800
Phillips 66,Petroleum industry,13000
Valero Energy,Petroleum industry,9743
Ford Motor Company,Automotive industry,173000
The Home Depot,Retail,471600
General Motors,Automotive,167000
Elevance Health,Healthcare,102200
JPMorgan Chase,Financial services,293723
Kroger,Retail,430000
Centene,Healthcare,74300
Verizon Communications,Telecommunications,117100
Walgreens Boots Alliance,Pharmaceutical industry,262500
Fannie Mae,Financials,8000
Comcast,Telecommunications,186000
AT&T,Conglomerate,160700
Meta Platforms,Technology,86482
Bank of America,Financials,216823
Target Corporation,Retail,440000
Dell Technologies,Technology,133000
Archer Daniels Midland,Food industry,41181
Citigroup,Financials,238104
United Parcel Service,Transportation,404700
Pfizer,Pharmaceutical industry,83000
Lowe's,Retail,244500
Johnson & Johnson,Pharmaceutical industry,152700
FedEx,Transportation,518249
Humana,Health Insurance,67100
Energy Transfer Partners,Petroleum industry,12565
State Farm,Financials,60519
Freddie Mac,Financials,7819
PepsiCo,Beverage,315000
Wells Fargo,Financials,238000
The Walt Disney Company,Media,195800
ConocoPhillips,Petroleum industry,9500
Tesla,Automotive and Energy,127855
Procter & Gamble,Consumer products Manufacturing,106000
United States Postal Service,Logistics,576000
Albertsons,Retail,198650
General Electric,Conglomerate,172000
MetLife,Financials,45000
Goldman Sachs,Financials,48500
Sysco,Food Service,70510
Bunge Limited,Food industry,23000
RTX Corporation,Conglomerate,182000
Boeing,Aerospace and defense,156000
StoneX Group,Financials,305
Lockheed Martin,Aerospace and Defense,116000
Morgan Stanley,Financials,82427
Intel,Technology,131900
HP,Technology,58000
TD Synnex,Infotech,28500
IBM,Technology,303100
HCA Healthcare,Healthcare,250500
Prudential Financial,Financials,39583
Caterpillar,Machinery,109100
Merck & Co.,Pharmaceutical industry,68000
World Fuel Services,Petroleum industry and Logistics,5214
New York Life Insurance Company,Insurance,15050
Enterprise Products,Petroleum industry,7300
AbbVie,Pharmaceutical industry,50000
Plains All American Pipeline,Petroleum industry,4100
Dow Chemical Company,Chemical industry,37800
AIG,Insurance,26200
American Express,Financial,77300
Publix,Retail,242000
Charter Communications,Telecommunications,101700
Tyson Foods,Food Processing,142000
John Deere,Agriculture manufacturing,82239
Cisco,Telecom Hardware Manufacturing,83300
Nationwide Mutual Insurance Company,Financial,24791
Allstate,Insurance,54250
Delta Air Lines,Airline,95000
Liberty Mutual,Insurance,50000
TJX,Retail,329000
Progressive Corporation,Insurance,55063
American Airlines,Airline,129700
CHS,Agriculture cooperative,10014
Performance Food Group,Food Processing,34825
PBF Energy,Petroleum industry,3616
Nike,Apparel,79100
Best Buy,Retail,71100
Bristol-Myers Squibb,Pharmaceutical industry,34300
United Airlines,Airline,92795
Thermo Fisher Scientific,Laboratory instruments,130000
Qualcomm,Technology,51000

In [77]:
# Can use filter with like arg and axis 0 to look up for the records
df2.filter(like = 'Corporation', axis = 0)

,Rank,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,,
McKesson Corporation,9,Health,276711,4.8%,48500,"Irving, Texas"
Chevron Corporation,10,Petroleum industry,246252,51.6%,43846,"San Ramon, California"
Target Corporation,33,Retail,109120,2.9%,440000,"Minneapolis, Minnesota"
RTX Corporation,59,Conglomerate,67074,4.2%,182000,"Arlington County, Virginia"
Progressive Corporation,90,Insurance,49611,4.0%,55063,"Mayfield Village, Ohio"

In [78]:
# Use of .loc function to filter bring the whole location of the item inside loc
df2.loc['Apple']

Rank                                          4
Industry                   Electronics industry
Revenue (USD millions)                   394328
Revenue growth                             7.8%
Employees                                164000
Headquarters              Cupertino, California
Name: Apple, dtype: object

In [79]:
# Use of .iloc function works like loc but with index number
df2.iloc[7]

Rank                                              8
Industry                                 Technology
Revenue (USD millions)                       282836
Revenue growth                                 9.8%
Employees                                    156000
Headquarters              Mountain View, California
Name: Alphabet, dtype: object

In [80]:
# .sort_values() function order and filter fuctions as wanted
df[df['Employees']>40000].sort_values(by='Employees')

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
34,35,Archer Daniels Midland,Food industry,101556,19.1%,41181,"Chicago, Illinois"
10,11,AmerisourceBergen,Pharmaceutical industry,238587,11.5%,41500,"Chesterbrook, Pennsylvania"
9,10,Chevron Corporation,Petroleum industry,246252,51.6%,43846,"San Ramon, California"
54,55,MetLife,Financials,69898,1.7%,45000,"New York City, New York"
13,14,Cardinal Health,Healthcare,181364,11.6%,46035,"Dublin, Ohio"
55,56,Goldman Sachs,Financials,68711,5.7%,48500,"New York City, New York"
8,9,McKesson Corporation,Health,276711,4.8%,48500,"Irving, Texas"
87,88,Liberty Mutual,Insurance,49956,3.6%,50000,"Boston, Massachusetts"
74,75,AbbVie,Pharmaceutical industry,58054,3.3%,50000,"Lake Bluff, Illinois"
99,100,Qualcomm,Technology,44200,31.7%,51000,"San Diego, California"
85,86,Allstate,Insurance,51412,3.4%,54250,"Northfield Township, Cook County, Illinois"
89,90,Progressive Corporation,Insurance,49611,4.0%,55063,"Mayfield Village, Ohio"
64,65,HP,Technology,62983,0.8%,58000,"Palo Alto, California"
43,44,State Farm,Financials,89328,8.6%,60519,"Bloomington, Illinois"
2,3,Exxon Mobil,Petroleum industry,413680,44.8%,62000,"Spring, Texas"
41,42,Humana,Health Insurance,92870,11.8%,67100,"Louisville, Kentucky"
70,71,Merck & Co.,Pharmaceutical industry,59283,15.8%,68000,"Kenilworth, New Jersey"
14,15,Cigna,Health Insurance,180516,3.7%,70231,"Bloomfield, Connecticut"
56,57,Sysco,Food Service,68636,33.8%,70510,"Houston, Texas"
95,96,Best Buy,Retail,46298,10.6%,71100,"Richfield, Minnesota"
24,25,Centene,Healthcare,144547,14.7%,74300,"St. Louis, Missouri"
78,79,American Express,Financial,55625,27.3%,77300,"New York City, New York"
94,95,Nike,Apparel,46710,4.9%,79100,"Beaverton, Oregon"
82,83,John Deere,Agriculture manufacturing,52577,19.4%,82239,"Moline, Illinois"
62,63,Morgan Stanley,Financials,65936,7.9%,82427,"New York City, New York"
37,38,Pfizer,Pharmaceutical industry,100330,23.4%,83000,"New York City, New York"
83,84,Cisco,Telecom Hardware Manufacturing,51557,3.5%,83300,"San Jose, California"
30,31,Meta Platforms,Technology,116609,1.1%,86482,"Menlo Park, California"
97,98,United Airlines,Airline,44955,82.5%,92795,"Chicago, Illinois"
86,87,Delta Air Lines,Airline,50582,69.2%,95000,"Atlanta, Georgia"
80,81,Charter Communications,Telecommunications,54022,4.5%,101700,"Stamford, Connecticut"
21,22,Elevance Health,Healthcare,156595,13.0%,102200,"Indianapolis, Indiana"
50,51,Procter & Gamble,Consumer products Manufacturing,80187,5.3%,106000,"Cincinnati, Ohio"
69,70,Caterpillar,Machinery,59427,16.6%,109100,"Deerfield, Illinois"
61,62,Lockheed Martin,Aerospace and Defense,65984,1.6%,116000,"Bethesda, Maryland"
25,26,Verizon Communications,Telecommunications,136835,2.4%,117100,"New York City, New York"
49,50,Tesla,Automotive and Energy,81462,51.4%,127855,"Austin, Texas"
90,91,American Airlines,Airline,48971,63.9%,129700,"Fort Worth, Texas"
98,99,Thermo Fisher Scientific,Laboratory instruments,44915,14.5%,130000,"Waltham, Massachusetts"
63,64,Intel,Technology,63054,20.1%,131900,"Santa Clara, California"
33,34,Dell Technologies,Technology,102301,4.4%,133000,"Round Rock, Texas"
81,82,Tyson Foods,Food Processing,53282,13.2%,142000,"Springdale, Arkansas"
39,40,Johnson & Johnson,Pharmaceutical industry,94943,1.2%,152700,"New Brunswick, New Jersey"
59,60,Boeing,Aerospace and defense,66608,6.9%,156000,"Chicago, Illinois"
7,8,Alphabet,Technology,282836,9.8%,156000,"Mountain View, California"
29,30,AT&T,Conglomerate,120741,28.5%,160700,"Dallas, Texas"
3,4,Apple,Electronics industry,394328,7.8%,164000,"Cupertino, California"
20,21,General Motors,Automotive,156735,23.4%,167000,"Detroit, Michigan"
53,54,General Electric,Conglomerate,76555,3.2%,172000,"Boston, Massachusetts"
18,19,Ford Motor Company,Automotive industry,158057,15.9%,173000,"Dearborn, Michigan"
58,59,RTX Corporation,Conglomerate,67074,4.2%,182000,"Arlington County, Virginia"
28,29,Comcast,Telecommunications,121427,4.3%,186000,"Philadelphia, Pennsylvania"
47,48,The Walt Disney Company,Media,82722,22.7%,195800,"Burbank, California"
52,53,Albertsons,Retail,77650,8.0%,198650,"Boise, Idaho"
31,32,Bank of America,Financials,115053,22.6%,216823,"Charlotte, North Carolina"
12,13,Microsoft,Technology,198270,18.0%,221000,"Redmond, Washington"
46,47,Wells Fargo,Financials,82859,0.5%,238000,"San Francisco, California"
35,36,Citigroup,Financials,101078,26.6%,238104,"New York City, New York"
79,80,Publix,Retail,54942,13.5%,242000,"Lakeland, Florida"
38,39,Lowe's,Retail,97059,0.8%,244500,"Mooresville, North Carolina"
67,68,HCA Healthcare,Healthcare,60233,2.5%,250500,"Nashville, Tennessee"
5,6,CVS Health,Healthcare,322467,10.4%,259500,"Woonsocket, Rhode Island"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,132703,10.7%,262500,"Deerfield, Illinois"
22,23,JPMorgan Chase,Financial services,154792,21.7%,293723,"New York City, New York"
66,67,IBM,Technology,60530,16.3%,303100,"Armonk, New York"
11,12,Costco,Retail,226954,15.8%,304000,"Issaquah, Washington"
45,46,PepsiCo,Beverage,86859,8.7%,315000,"Purchase, New York"
88,89,TJX,Retail,49936,2.9%,329000,"Framingham, Massachusetts"
6,7,Berkshire Hathaway,Conglomerate,302089,9.4%,383000,"Omaha, Nebraska"
4,5,UnitedHealth Group,Healthcare,324162,12.7%,400000,"Minnetonka, Minnesota"
36,37,United Parcel Service,Transportation,100338,3.1%,404700,"Atlanta, Georgia"
23,24,Kroger,Retail,148258,7.5%,430000,"Cincinnati, Ohio"
32,33,Target Corporation,Retail,109120,2.9%,440000,"Minneapolis, Minnesota"
19,20,The Home Depot,Retail,157403,4.1%,471600,"Atlanta, Georgia"
40,41,FedEx,Transportation,93512,11.4%,518249,"Memphis, Tennessee"
51,52,United States Postal Service,Logistics,78620,2.0%,576000,"Washington, D.C."
1,2,Amazon,Retail and Cloud Computing,513983,9.4%,1540000,"Seattle, Washington"
0,1,Walmart,Retail,611289,6.7%,2100000,"Bentonville, Arkansas"

In [81]:
# sort by multiple columns with a list and ascending and descending

In [82]:
df[df['Revenue (USD millions)'] > 100000].sort_values(by=['Employees','Revenue (USD millions)'], ascending =[True, False])

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
27,28,Fannie Mae,Financials,121596,19.7%,8000,"Washington, D.C."
17,18,Valero Energy,Petroleum industry,171189,58.0%,9743,"San Antonio, Texas"
16,17,Phillips 66,Petroleum industry,175702,53.0%,13000,"Houston, Texas"
15,16,Marathon Petroleum,Petroleum industry,180012,27.6%,17800,"Findlay, Ohio"
34,35,Archer Daniels Midland,Food industry,101556,19.1%,41181,"Chicago, Illinois"
10,11,AmerisourceBergen,Pharmaceutical industry,238587,11.5%,41500,"Chesterbrook, Pennsylvania"
9,10,Chevron Corporation,Petroleum industry,246252,51.6%,43846,"San Ramon, California"
13,14,Cardinal Health,Healthcare,181364,11.6%,46035,"Dublin, Ohio"
8,9,McKesson Corporation,Health,276711,4.8%,48500,"Irving, Texas"
2,3,Exxon Mobil,Petroleum industry,413680,44.8%,62000,"Spring, Texas"
14,15,Cigna,Health Insurance,180516,3.7%,70231,"Bloomfield, Connecticut"
24,25,Centene,Healthcare,144547,14.7%,74300,"St. Louis, Missouri"
37,38,Pfizer,Pharmaceutical industry,100330,23.4%,83000,"New York City, New York"
30,31,Meta Platforms,Technology,116609,1.1%,86482,"Menlo Park, California"
21,22,Elevance Health,Healthcare,156595,13.0%,102200,"Indianapolis, Indiana"
25,26,Verizon Communications,Telecommunications,136835,2.4%,117100,"New York City, New York"
33,34,Dell Technologies,Technology,102301,4.4%,133000,"Round Rock, Texas"
7,8,Alphabet,Technology,282836,9.8%,156000,"Mountain View, California"
29,30,AT&T,Conglomerate,120741,28.5%,160700,"Dallas, Texas"
3,4,Apple,Electronics industry,394328,7.8%,164000,"Cupertino, California"
20,21,General Motors,Automotive,156735,23.4%,167000,"Detroit, Michigan"
18,19,Ford Motor Company,Automotive industry,158057,15.9%,173000,"Dearborn, Michigan"
28,29,Comcast,Telecommunications,121427,4.3%,186000,"Philadelphia, Pennsylvania"
31,32,Bank of America,Financials,115053,22.6%,216823,"Charlotte, North Carolina"
12,13,Microsoft,Technology,198270,18.0%,221000,"Redmond, Washington"
35,36,Citigroup,Financials,101078,26.6%,238104,"New York City, New York"
5,6,CVS Health,Healthcare,322467,10.4%,259500,"Woonsocket, Rhode Island"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,132703,10.7%,262500,"Deerfield, Illinois"
22,23,JPMorgan Chase,Financial services,154792,21.7%,293723,"New York City, New York"
11,12,Costco,Retail,226954,15.8%,304000,"Issaquah, Washington"
6,7,Berkshire Hathaway,Conglomerate,302089,9.4%,383000,"Omaha, Nebraska"
4,5,UnitedHealth Group,Healthcare,324162,12.7%,400000,"Minnetonka, Minnesota"
36,37,United Parcel Service,Transportation,100338,3.1%,404700,"Atlanta, Georgia"
23,24,Kroger,Retail,148258,7.5%,430000,"Cincinnati, Ohio"
32,33,Target Corporation,Retail,109120,2.9%,440000,"Minneapolis, Minnesota"
19,20,The Home Depot,Retail,157403,4.1%,471600,"Atlanta, Georgia"
1,2,Amazon,Retail and Cloud Computing,513983,9.4%,1540000,"Seattle, Washington"
0,1,Walmart,Retail,611289,6.7%,2100000,"Bentonville, Arkansas"

In [83]:
# Indexing set an index with .set_index() and remove the index with .reset_index()
df = df.set_index('Name')
df

,Rank,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,,
Walmart,1,Retail,611289,6.7%,2100000,"Bentonville, Arkansas"
Amazon,2,Retail and Cloud Computing,513983,9.4%,1540000,"Seattle, Washington"
Exxon Mobil,3,Petroleum industry,413680,44.8%,62000,"Spring, Texas"
Apple,4,Electronics industry,394328,7.8%,164000,"Cupertino, California"
UnitedHealth Group,5,Healthcare,324162,12.7%,400000,"Minnetonka, Minnesota"
CVS Health,6,Healthcare,322467,10.4%,259500,"Woonsocket, Rhode Island"
Berkshire Hathaway,7,Conglomerate,302089,9.4%,383000,"Omaha, Nebraska"
Alphabet,8,Technology,282836,9.8%,156000,"Mountain View, California"
McKesson Corporation,9,Health,276711,4.8%,48500,"Irving, Texas"
Chevron Corporation,10,Petroleum industry,246252,51.6%,43846,"San Ramon, California"
AmerisourceBergen,11,Pharmaceutical industry,238587,11.5%,41500,"Chesterbrook, Pennsylvania"
Costco,12,Retail,226954,15.8%,304000,"Issaquah, Washington"
Microsoft,13,Technology,198270,18.0%,221000,"Redmond, Washington"
Cardinal Health,14,Healthcare,181364,11.6%,46035,"Dublin, Ohio"
Cigna,15,Health Insurance,180516,3.7%,70231,"Bloomfield, Connecticut"
Marathon Petroleum,16,Petroleum industry,180012,27.6%,17800,"Findlay, Ohio"
Phillips 66,17,Petroleum industry,175702,53.0%,13000,"Houston, Texas"
Valero Energy,18,Petroleum industry,171189,58.0%,9743,"San Antonio, Texas"
Ford Motor Company,19,Automotive industry,158057,15.9%,173000,"Dearborn, Michigan"
The Home Depot,20,Retail,157403,4.1%,471600,"Atlanta, Georgia"
General Motors,21,Automotive,156735,23.4%,167000,"Detroit, Michigan"
Elevance Health,22,Healthcare,156595,13.0%,102200,"Indianapolis, Indiana"
JPMorgan Chase,23,Financial services,154792,21.7%,293723,"New York City, New York"
Kroger,24,Retail,148258,7.5%,430000,"Cincinnati, Ohio"
Centene,25,Healthcare,144547,14.7%,74300,"St. Louis, Missouri"
Verizon Communications,26,Telecommunications,136835,2.4%,117100,"New York City, New York"
Walgreens Boots Alliance,27,Pharmaceutical industry,132703,10.7%,262500,"Deerfield, Illinois"
Fannie Mae,28,Financials,121596,19.7%,8000,"Washington, D.C."
Comcast,29,Telecommunications,121427,4.3%,186000,"Philadelphia, Pennsylvania"
AT&T,30,Conglomerate,120741,28.5%,160700,"Dallas, Texas"
Meta Platforms,31,Technology,116609,1.1%,86482,"Menlo Park, California"
Bank of America,32,Financials,115053,22.6%,216823,"Charlotte, North Carolina"
Target Corporation,33,Retail,109120,2.9%,440000,"Minneapolis, Minnesota"
Dell Technologies,34,Technology,102301,4.4%,133000,"Round Rock, Texas"
Archer Daniels Midland,35,Food industry,101556,19.1%,41181,"Chicago, Illinois"
Citigroup,36,Financials,101078,26.6%,238104,"New York City, New York"
United Parcel Service,37,Transportation,100338,3.1%,404700,"Atlanta, Georgia"
Pfizer,38,Pharmaceutical industry,100330,23.4%,83000,"New York City, New York"
Lowe's,39,Retail,97059,0.8%,244500,"Mooresville, North Carolina"
Johnson & Johnson,40,Pharmaceutical industry,94943,1.2%,152700,"New Brunswick, New Jersey"
FedEx,41,Transportation,93512,11.4%,518249,"Memphis, Tennessee"
Humana,42,Health Insurance,92870,11.8%,67100,"Louisville, Kentucky"
Energy Transfer Partners,43,Petroleum industry,89876,33.3%,12565,"Dallas, Texas"
State Farm,44,Financials,89328,8.6%,60519,"Bloomington, Illinois"
Freddie Mac,45,Financials,86717,31.6%,7819,"McLean, Virginia"
PepsiCo,46,Beverage,86859,8.7%,315000,"Purchase, New York"
Wells Fargo,47,Financials,82859,0.5%,238000,"San Francisco, California"
The Walt Disney Company,48,Media,82722,22.7%,195800,"Burbank, California"
ConocoPhillips,49,Petroleum industry,82156,69.9%,9500,"Houston, Texas"
Tesla,50,Automotive and Energy,81462,51.4%,127855,"Austin, Texas"
Procter & Gamble,51,Consumer products Manufacturing,80187,5.3%,106000,"Cincinnati, Ohio"
United States Postal Service,52,Logistics,78620,2.0%,576000,"Washington, D.C."
Albertsons,53,Retail,77650,8.0%,198650,"Boise, Idaho"
General Electric,54,Conglomerate,76555,3.2%,172000,"Boston, Massachusetts"
MetLife,55,Financials,69898,1.7%,45000,"New York City, New York"
Goldman Sachs,56,Financials,68711,5.7%,48500,"New York City, New York"
Sysco,57,Food Service,68636,33.8%,70510,"Houston, Texas"
Bunge Limited,58,Food industry,67232,13.7%,23000,"White Plains, New York"
RTX Corporation,59,Conglomerate,67074,4.2%,182000,"Arlington County, Virginia"
Boeing,60,Aerospace and defense,66608,6.9%,156000,"Chicago, Illinois"
StoneX Group,61,Financials,66036,55.3%,305,"New York City, New York"
Lockheed Martin,62,Aerospace and Defense,65984,1.6%,116000,"Bethesda, Maryland"
Morgan Stanley,63,Financials,65936,7.9%,82427,"New York City, New York"
Intel,64,Technology,63054,20.1%,131900,"Santa Clara, California"
HP,65,Technology,62983,0.8%,58000,"Palo Alto, California"
TD Synnex,66,Infotech,62344,97.2%,28500,"Clearwater, Florida"
IBM,67,Technology,60530,16.3%,303100,"Armonk, New York"
HCA Healthcare,68,Healthcare,60233,2.5%,250500,"Nashville, Tennessee"
Prudential Financial,69,Financials,60050,15.3%,39583,"Newark, New Jersey"
Caterpillar,70,Machinery,59427,16.6%,109100,"Deerfield, Illinois"
Merck & Co.,71,Pharmaceutical industry,59283,15.8%,68000,"Kenilworth, New Jersey"
World Fuel Services,72,Petroleum industry and Logistics,59043,88.4%,5214,"Miami, Florida"
New York Life Insurance Company,73,Insurance,58445,14.2%,15050,"New York City, New York"
Enterprise Products,74,Petroleum industry,58186,42.6%,7300,"Houston, Texas"
AbbVie,75,Pharmaceutical industry,58054,3.3%,50000,"Lake Bluff, Illinois"
Plains All American Pipeline,76,Petroleum industry,57342,36.3%,4100,"Houston, Texas"
Dow Chemical Company,77,Chemical industry,56902,3.5%,37800,"Midland, Michigan"
AIG,78,Insurance,56437,8.4%,26200,"New York City, New York"
American Express,79,Financial,55625,27.3%,77300,"New York City, New York"
Publix,80,Retail,54942,13.5%,242000,"Lakeland, Florida"
Charter Communications,81,Telecommunications,54022,4.5%,101700,"Stamford, Connecticut"
Tyson Foods,82,Food Processing,53282,13.2%,142000,"Springdale, Arkansas"
John Deere,83,Agriculture manufacturing,52577,19.4%,82239,"Moline, Illinois"
Cisco,84,Telecom Hardware Manufacturing,51557,3.5%,83300,"San Jose, California"
Nationwide Mutual Insurance Company,85,Financial,51450,8.6%,24791,"Columbus, Ohio"
Allstate,86,Insurance,51412,3.4%,54250,"Northfield Township, Cook County, Illinois"
Delta Air Lines,87,Airline,50582,69.2%,95000,"Atlanta, Georgia"
Liberty Mutual,88,Insurance,49956,3.6%,50000,"Boston, Massachusetts"
TJX,89,Retail,49936,2.9%,329000,"Framingham, Massachusetts"
Progressive Corporation,90,Insurance,49611,4.0%,55063,"Mayfield Village, Ohio"
American Airlines,91,Airline,48971,63.9%,129700,"Fort Worth, Texas"
CHS,92,Agriculture cooperative,47194,24.3%,10014,"Inver Grove Heights, Minnesota"
Performance Food Group,93,Food Processing,47194,61.6%,34825,"Richmond, Virginia"
PBF Energy,94,Petroleum industry,46830,71.8%,3616,"Parsippany–Troy Hills, New Jersey"
Nike,95,Apparel,46710,4.9%,79100,"Beaverton, Oregon"
Best Buy,96,Retail,46298,10.6%,71100,"Richfield, Minnesota"
Bristol-Myers Squibb,97,Pharmaceutical industry,46159,0.5%,34300,"New York City, New York"
United Airlines,98,Airline,44955,82.5%,92795,"Chicago, Illinois"
Thermo Fisher Scientific,99,Laboratory instruments,44915,14.5%,130000,"Waltham, Massachusetts"
Qualcomm,100,Technology,44200,31.7%,51000,"San Diego, California"

In [93]:
# Remove the index with .reset_index() use inplace to save changes.
df.reset_index(inplace = True)

In [85]:
# Search through indexes with loc[] by its str name.
df2.loc['Amazon']

Rank                                               2
Industry                  Retail and Cloud Computing
Revenue (USD millions)                        513983
Revenue growth                                  9.4%
Employees                                    1540000
Headquarters                     Seattle, Washington
Name: Amazon, dtype: object

In [94]:
# Multiple Indexes with a list to add more than 1 column.
df = df.set_index(['Industry', 'Name','Rank'])
df

                                                                           Revenue (USD millions)  \
Industry                         Name                                Rank
Retail                           Walmart                             1                     611289
Retail and Cloud Computing       Amazon                              2                     513983
Petroleum industry               Exxon Mobil                         3                     413680
Electronics industry             Apple                               4                     394328
Healthcare                       UnitedHealth Group                  5                     324162
                                 CVS Health                          6                     322467
Conglomerate                     Berkshire Hathaway                  7                     302089
Technology                       Alphabet                            8                     282836
Health                           McKesson Corporation                9                     276711
Petroleum industry               Chevron Corporation                 10                    246252
Pharmaceutical industry          AmerisourceBergen                   11                    238587
Retail                           Costco                              12                    226954
Technology                       Microsoft                           13                    198270
Healthcare                       Cardinal Health                     14                    181364
Health Insurance                 Cigna                               15                    180516
Petroleum industry               Marathon Petroleum                  16                    180012
                                 Phillips 66                         17                    175702
                                 Valero Energy                       18                    171189
Automotive industry              Ford Motor Company                  19                    158057
Retail                           The Home Depot                      20                    157403
Automotive                       General Motors                      21                    156735
Healthcare                       Elevance Health                     22                    156595
Financial services               JPMorgan Chase                      23                    154792
Retail                           Kroger                              24                    148258
Healthcare                       Centene                             25                    144547
Telecommunications               Verizon Communications              26                    136835
Pharmaceutical industry          Walgreens Boots Alliance            27                    132703
Financials                       Fannie Mae                          28                    121596
Telecommunications               Comcast                             29                    121427
Conglomerate                     AT&T                                30                    120741
Technology                       Meta Platforms                      31                    116609
Financials                       Bank of America                     32                    115053
Retail                           Target Corporation                  33                    109120
Technology                       Dell Technologies                   34                    102301
Food industry                    Archer Daniels Midland              35                    101556
Financials                       Citigroup                           36                    101078
Transportation                   United Parcel Service               37                    100338
Pharmaceutical industry          Pfizer                              38                    100330
Retail                           Lowe's                              39                     97059
Pharmaceutical industry          Johnson & Johnson                   40                     94943
Transportation                   FedEx                               41                     93512
Health Insurance                 Humana                              42                     92870
Petroleum industry               Energy Transfer Partners            43                     89876
Financials                       State Farm                          44                     89328
                                 Freddie Mac                         45                     86717
Beverage                         PepsiCo                             46                     86859
Financials                       Wells Fargo                         47                     82859
Media                            The Walt Disney Company             48                     82722
Petroleum industry               ConocoPhillips                      49                     82156
Automotive and Energy            Tesla                               50                     81462
Consumer products Manufacturing  Procter & Gamble                    51                     80187
Logistics                        United States Postal Service        52                     78620
Retail                           Albertsons                          53                     77650
Conglomerate                     General Electric                    54                     76555
Financials                       MetLife                             55                     69898
                                 Goldman Sachs                       56                     68711
Food Service                     Sysco                               57                     68636
Food industry                    Bunge Limited                       58                     67232
Conglomerate                     RTX Corporation                     59                     67074
Aerospace and defense            Boeing                              60                     66608
Financials                       StoneX Group                        61                     66036
Aerospace and Defense            Lockheed Martin                     62                     65984
Financials                       Morgan Stanley                      63                     65936
Technology                       Intel                               64                     63054
                                 HP                                  65                     62983
Infotech                         TD Synnex                           66                     62344
Technology                       IBM                                 67                     60530
Healthcare                       HCA Healthcare                      68                     60233
Financials                       Prudential Financial                69                     60050
Machinery                        Caterpillar                         70                     59427
Pharmaceutical industry          Merck & Co.                         71                     59283
Petroleum industry and Logistics World Fuel Services                 72                     59043
Insurance                        New York Life Insurance Company     73                     58445
Petroleum industry               Enterprise Products                 74                     58186
Pharmaceutical industry          AbbVie                              75                     58054
Petroleum industry               Plains All American Pipeline        76                     57342
Chemical industry                Dow Chemical Company                77                     56902
Insurance                        AIG                                 78                     56437
Financial                        American Express                    79                     55625
Retail                           Publix                              80                     54942
Telecommunications               Charter Communications              81                     54022
Food Processing                  Tyson Foods                         82                     53282
Agriculture manufacturing        John Deere                          83                     52577
Telecom Hardware Manufacturing   Cisco                               84                     51557
Financial                        Nationwide Mutual Insurance Company 85                     51450
Insurance                        Allstate                            86                     51412
Airline                          Delta Air Lines                     87                     50582
Insurance                        Liberty Mutual                      88                     49956
Retail                           TJX                                 89                     49936
Insurance                        Progressive Corporation             90                     49611
Airline                          American Airlines                   91                     48971
Agriculture cooperative          CHS                                 92                     47194
Food Processing                  Performance Food Group              93                     47194
Petroleum industry               PBF Energy                          94                     46830
Apparel                          Nike                                95                     46710
Retail                           Best Buy                            96                     46298
Pharmaceutical industry          Bristol-Myers Squibb                97                     46159
Airline                          United Airlines                     98                     44955
Laboratory instruments           Thermo Fisher Scientific            99                     44915
Technology                       Qualcomm                            100                    44200

                                                                          Revenue growth  \
Industry                         Name                                Rank
Retail                           Walmart                             1              6.7%
Retail and Cloud Computing       Amazon                              2              9.4%
Petroleum industry               Exxon Mobil                         3             44.8%
Electronics industry             Apple                               4              7.8%
Healthcare                       UnitedHealth Group                  5             12.7%
                                 CVS Health                          6             10.4%
Conglomerate                     Berkshire Hathaway                  7              9.4%
Technology                       Alphabet                            8              9.8%
Health                           McKesson Corporation                9              4.8%
Petroleum industry               Chevron Corporation                 10            51.6%
Pharmaceutical industry          AmerisourceBergen                   11            11.5%
Retail                           Costco                              12            15.8%
Technology                       Microsoft                           13            18.0%
Healthcare                       Cardinal Health                     14            11.6%
Health Insurance                 Cigna                               15             3.7%
Petroleum industry               Marathon Petroleum                  16            27.6%
                                 Phillips 66                         17            53.0%
                                 Valero Energy                       18            58.0%
Automotive industry              Ford Motor Company                  19            15.9%
Retail                           The Home Depot                      20             4.1%
Automotive                       General Motors                      21            23.4%
Healthcare                       Elevance Health                     22            13.0%
Financial services               JPMorgan Chase                      23            21.7%
Retail                           Kroger                              24             7.5%
Healthcare                       Centene                             25            14.7%
Telecommunications               Verizon Communications              26             2.4%
Pharmaceutical industry          Walgreens Boots Alliance            27            10.7%
Financials                       Fannie Mae                          28            19.7%
Telecommunications               Comcast                             29             4.3%
Conglomerate                     AT&T                                30            28.5%
Technology                       Meta Platforms                      31             1.1%
Financials                       Bank of America                     32            22.6%
Retail                           Target Corporation                  33             2.9%
Technology                       Dell Technologies                   34             4.4%
Food industry                    Archer Daniels Midland              35            19.1%
Financials                       Citigroup                           36            26.6%
Transportation                   United Parcel Service               37             3.1%
Pharmaceutical industry          Pfizer                              38            23.4%
Retail                           Lowe's                              39             0.8%
Pharmaceutical industry          Johnson & Johnson                   40             1.2%
Transportation                   FedEx                               41            11.4%
Health Insurance                 Humana                              42            11.8%
Petroleum industry               Energy Transfer Partners            43            33.3%
Financials                       State Farm                          44             8.6%
                                 Freddie Mac                         45            31.6%
Beverage                         PepsiCo                             46             8.7%
Financials                       Wells Fargo                         47             0.5%
Media                            The Walt Disney Company             48            22.7%
Petroleum industry               ConocoPhillips                      49            69.9%
Automotive and Energy            Tesla                               50            51.4%
Consumer products Manufacturing  Procter & Gamble                    51             5.3%
Logistics                        United States Postal Service        52             2.0%
Retail                           Albertsons                          53             8.0%
Conglomerate                     General Electric                    54             3.2%
Financials                       MetLife                             55             1.7%
                                 Goldman Sachs                       56             5.7%
Food Service                     Sysco                               57            33.8%
Food industry                    Bunge Limited                       58            13.7%
Conglomerate                     RTX Corporation                     59             4.2%
Aerospace and defense            Boeing                              60             6.9%
Financials                       StoneX Group                        61            55.3%
Aerospace and Defense            Lockheed Martin                     62             1.6%
Financials                       Morgan Stanley                      63             7.9%
Technology                       Intel                               64            20.1%
                                 HP                                  65             0.8%
Infotech                         TD Synnex                           66            97.2%
Technology                       IBM                                 67            16.3%
Healthcare                       HCA Healthcare                      68             2.5%
Financials                       Prudential Financial                69            15.3%
Machinery                        Caterpillar                         70            16.6%
Pharmaceutical industry          Merck & Co.                         71            15.8%
Petroleum industry and Logistics World Fuel Services                 72            88.4%
Insurance                        New York Life Insurance Company     73            14.2%
Petroleum industry               Enterprise Products                 74            42.6%
Pharmaceutical industry          AbbVie                              75             3.3%
Petroleum industry               Plains All American Pipeline        76            36.3%
Chemical industry                Dow Chemical Company                77             3.5%
Insurance                        AIG                                 78             8.4%
Financial                        American Express                    79            27.3%
Retail                           Publix                              80            13.5%
Telecommunications               Charter Communications              81             4.5%
Food Processing                  Tyson Foods                         82            13.2%
Agriculture manufacturing        John Deere                          83            19.4%
Telecom Hardware Manufacturing   Cisco                               84             3.5%
Financial                        Nationwide Mutual Insurance Company 85             8.6%
Insurance                        Allstate                            86             3.4%
Airline                          Delta Air Lines                     87            69.2%
Insurance                        Liberty Mutual                      88             3.6%
Retail                           TJX                                 89             2.9%
Insurance                        Progressive Corporation             90             4.0%
Airline                          American Airlines                   91            63.9%
Agriculture cooperative          CHS                                 92            24.3%
Food Processing                  Performance Food Group              93            61.6%
Petroleum industry               PBF Energy                          94            71.8%
Apparel                          Nike                                95             4.9%
Retail                           Best Buy                            96            10.6%
Pharmaceutical industry          Bristol-Myers Squibb                97             0.5%
Airline                          United Airlines                     98            82.5%
Laboratory instruments           Thermo Fisher Scientific            99            14.5%
Technology                       Qualcomm                            100           31.7%

                                                                           Employees  \
Industry                         Name                                Rank
Retail                           Walmart                             1       2100000
Retail and Cloud Computing       Amazon                              2       1540000
Petroleum industry               Exxon Mobil                         3         62000
Electronics industry             Apple                               4        164000
Healthcare                       UnitedHealth Group                  5        400000
                                 CVS Health                          6        259500
Conglomerate                     Berkshire Hathaway                  7        383000
Technology                       Alphabet                            8        156000
Health                           McKesson Corporation                9         48500

In [95]:
# Sort Index alphabetically with sort_index()
df = df.sort_index()
df

                                                                           Revenue (USD millions)  \
Industry                         Name                                Rank
Aerospace and Defense            Lockheed Martin                     62                     65984
Aerospace and defense            Boeing                              60                     66608
Agriculture cooperative          CHS                                 92                     47194
Agriculture manufacturing        John Deere                          83                     52577
Airline                          American Airlines                   91                     48971
                                 Delta Air Lines                     87                     50582
                                 United Airlines                     98                     44955
Apparel                          Nike                                95                     46710
Automotive                       General Motors                      21                    156735
Automotive and Energy            Tesla                               50                     81462
Automotive industry              Ford Motor Company                  19                    158057
Beverage                         PepsiCo                             46                     86859
Chemical industry                Dow Chemical Company                77                     56902
Conglomerate                     AT&T                                30                    120741
                                 Berkshire Hathaway                  7                     302089
                                 General Electric                    54                     76555
                                 RTX Corporation                     59                     67074
Consumer products Manufacturing  Procter & Gamble                    51                     80187
Electronics industry             Apple                               4                     394328
Financial                        American Express                    79                     55625
                                 Nationwide Mutual Insurance Company 85                     51450
Financial services               JPMorgan Chase                      23                    154792
Financials                       Bank of America                     32                    115053
                                 Citigroup                           36                    101078
                                 Fannie Mae                          28                    121596
                                 Freddie Mac                         45                     86717
                                 Goldman Sachs                       56                     68711
                                 MetLife                             55                     69898
                                 Morgan Stanley                      63                     65936
                                 Prudential Financial                69                     60050
                                 State Farm                          44                     89328
                                 StoneX Group                        61                     66036
                                 Wells Fargo                         47                     82859
Food Processing                  Performance Food Group              93                     47194
                                 Tyson Foods                         82                     53282
Food Service                     Sysco                               57                     68636
Food industry                    Archer Daniels Midland              35                    101556
                                 Bunge Limited                       58                     67232
Health                           McKesson Corporation                9                     276711
Health Insurance                 Cigna                               15                    180516
                                 Humana                              42                     92870
Healthcare                       CVS Health                          6                     322467
                                 Cardinal Health                     14                    181364
                                 Centene                             25                    144547
                                 Elevance Health                     22                    156595
                                 HCA Healthcare                      68                     60233
                                 UnitedHealth Group                  5                     324162
Infotech                         TD Synnex                           66                     62344
Insurance                        AIG                                 78                     56437
                                 Allstate                            86                     51412
                                 Liberty Mutual                      88                     49956
                                 New York Life Insurance Company     73                     58445
                                 Progressive Corporation             90                     49611
Laboratory instruments           Thermo Fisher Scientific            99                     44915
Logistics                        United States Postal Service        52                     78620
Machinery                        Caterpillar                         70                     59427
Media                            The Walt Disney Company             48                     82722
Petroleum industry               Chevron Corporation                 10                    246252
                                 ConocoPhillips                      49                     82156
                                 Energy Transfer Partners            43                     89876
                                 Enterprise Products                 74                     58186
                                 Exxon Mobil                         3                     413680
                                 Marathon Petroleum                  16                    180012
                                 PBF Energy                          94                     46830
                                 Phillips 66                         17                    175702
                                 Plains All American Pipeline        76                     57342
                                 Valero Energy                       18                    171189
Petroleum industry and Logistics World Fuel Services                 72                     59043
Pharmaceutical industry          AbbVie                              75                     58054
                                 AmerisourceBergen                   11                    238587
                                 Bristol-Myers Squibb                97                     46159
                                 Johnson & Johnson                   40                     94943
                                 Merck & Co.                         71                     59283
                                 Pfizer                              38                    100330
                                 Walgreens Boots Alliance            27                    132703
Retail                           Albertsons                          53                     77650
                                 Best Buy                            96                     46298
                                 Costco                              12                    226954
                                 Kroger                              24                    148258
                                 Lowe's                              39                     97059
                                 Publix                              80                     54942
                                 TJX                                 89                     49936
                                 Target Corporation                  33                    109120
                                 The Home Depot                      20                    157403
                                 Walmart                             1                     611289
Retail and Cloud Computing       Amazon                              2                     513983
Technology                       Alphabet                            8                     282836
                                 Dell Technologies                   34                    102301
                                 HP                                  65                     62983
                                 IBM                                 67                     60530
                                 Intel                               64                     63054
                                 Meta Platforms                      31                    116609
                                 Microsoft                           13                    198270
                                 Qualcomm                            100                    44200
Telecom Hardware Manufacturing   Cisco                               84                     51557
Telecommunications               Charter Communications              81                     54022
                                 Comcast                             29                    121427
                                 Verizon Communications              26                    136835
Transportation                   FedEx                               41                     93512
                                 United Parcel Service               37                    100338

                                                                          Revenue growth  \
Industry                         Name                                Rank
Aerospace and Defense            Lockheed Martin                     62             1.6%
Aerospace and defense            Boeing                              60             6.9%
Agriculture cooperative          CHS                                 92            24.3%
Agriculture manufacturing        John Deere                          83            19.4%
Airline                          American Airlines                   91            63.9%
                                 Delta Air Lines                     87            69.2%
                                 United Airlines                     98            82.5%
Apparel                          Nike                                95             4.9%
Automotive                       General Motors                      21            23.4%
Automotive and Energy            Tesla                               50            51.4%
Automotive industry              Ford Motor Company                  19            15.9%
Beverage                         PepsiCo                             46             8.7%
Chemical industry                Dow Chemical Company                77             3.5%
Conglomerate                     AT&T                                30            28.5%
                                 Berkshire Hathaway                  7              9.4%
                                 General Electric                    54             3.2%
                                 RTX Corporation                     59             4.2%
Consumer products Manufacturing  Procter & Gamble                    51             5.3%
Electronics industry             Apple                               4              7.8%
Financial                        American Express                    79            27.3%
                                 Nationwide Mutual Insurance Company 85             8.6%
Financial services               JPMorgan Chase                      23            21.7%
Financials                       Bank of America                     32            22.6%
                                 Citigroup                           36            26.6%
                                 Fannie Mae                          28            19.7%
                                 Freddie Mac                         45            31.6%
                                 Goldman Sachs                       56             5.7%
                                 MetLife                             55             1.7%
                                 Morgan Stanley                      63             7.9%
                                 Prudential Financial                69            15.3%
                                 State Farm                          44             8.6%
                                 StoneX Group                        61            55.3%
                                 Wells Fargo                         47             0.5%
Food Processing                  Performance Food Group              93            61.6%
                                 Tyson Foods                         82            13.2%
Food Service                     Sysco                               57            33.8%
Food industry                    Archer Daniels Midland              35            19.1%
                                 Bunge Limited                       58            13.7%
Health                           McKesson Corporation                9              4.8%
Health Insurance                 Cigna                               15             3.7%
                                 Humana                              42            11.8%
Healthcare                       CVS Health                          6             10.4%
                                 Cardinal Health                     14            11.6%
                                 Centene                             25            14.7%
                                 Elevance Health                     22            13.0%
                                 HCA Healthcare                      68             2.5%
                                 UnitedHealth Group                  5             12.7%
Infotech                         TD Synnex                           66            97.2%
Insurance                        AIG                                 78             8.4%
                                 Allstate                            86             3.4%
                                 Liberty Mutual                      88             3.6%
                                 New York Life Insurance Company     73            14.2%
                                 Progressive Corporation             90             4.0%
Laboratory instruments           Thermo Fisher Scientific            99            14.5%
Logistics                        United States Postal Service        52             2.0%
Machinery                        Caterpillar                         70            16.6%
Media                            The Walt Disney Company             48            22.7%
Petroleum industry               Chevron Corporation                 10            51.6%
                                 ConocoPhillips                      49            69.9%
                                 Energy Transfer Partners            43            33.3%
                                 Enterprise Products                 74            42.6%
                                 Exxon Mobil                         3             44.8%
                                 Marathon Petroleum                  16            27.6%
                                 PBF Energy                          94            71.8%
                                 Phillips 66                         17            53.0%
                                 Plains All American Pipeline        76            36.3%
                                 Valero Energy                       18            58.0%
Petroleum industry and Logistics World Fuel Services                 72            88.4%
Pharmaceutical industry          AbbVie                              75             3.3%
                                 AmerisourceBergen                   11            11.5%
                                 Bristol-Myers Squibb                97             0.5%
                                 Johnson & Johnson                   40             1.2%
                                 Merck & Co.                         71            15.8%
                                 Pfizer                              38            23.4%
                                 Walgreens Boots Alliance            27            10.7%
Retail                           Albertsons                          53             8.0%
                                 Best Buy                            96            10.6%
                                 Costco                              12            15.8%
                                 Kroger                              24             7.5%
                                 Lowe's                              39             0.8%
                                 Publix                              80            13.5%
                                 TJX                                 89             2.9%
                                 Target Corporation                  33             2.9%
                                 The Home Depot                      20             4.1%
                                 Walmart                             1              6.7%
Retail and Cloud Computing       Amazon                              2              9.4%
Technology                       Alphabet                            8              9.8%
                                 Dell Technologies                   34             4.4%
                                 HP                                  65             0.8%
                                 IBM                                 67            16.3%
                                 Intel                               64            20.1%
                                 Meta Platforms                      31             1.1%
                                 Microsoft                           13            18.0%
                                 Qualcomm                            100           31.7%
Telecom Hardware Manufacturing   Cisco                               84             3.5%
Telecommunications               Charter Communications              81             4.5%
                                 Comcast                             29             4.3%
                                 Verizon Communications              26             2.4%
Transportation                   FedEx                               41            11.4%
                                 United Parcel Service               37             3.1%

                                                                           Employees  \
Industry                         Name                                Rank
Aerospace and Defense            Lockheed Martin                     62       116000
Aerospace and defense            Boeing                              60       156000
Agriculture cooperative          CHS                                 92        10014
Agriculture manufacturing        John Deere                          83        82239
Airline                          American Airlines                   91       129700
                                 Delta Air Lines                     87        95000
                                 United Airlines                     98        92795
Apparel                          Nike                                95        79100
Automotive                       General Motors                      21       167000

In [104]:
# Search by multiple indexes with loc[]
df.loc['Petroleum industry','Chevron Corporation']

      Revenue (USD millions) Revenue growth  Employees           Headquarters
Rank
10                    246252          51.6%      43846  San Ramon, California

In [110]:
# Group By in pandas with .groupby() on Industry column
df.reset_index(inplace = True)
df.set_index('Rank',inplace = True)
df = df.sort_index()
df_group_by_frame = df.groupby('Industry')
df_group_by_frame

In [112]:
# Add aggregations to the group by function in order to get an output like mean() as an aggregate function.
df_group_by_frame.mean('Revenue (USD millions)')

                                  Revenue (USD millions)     Employees
Industry
Aerospace and Defense                       65984.000000  1.160000e+05
Aerospace and defense                       66608.000000  1.560000e+05
Agriculture cooperative                     47194.000000  1.001400e+04
Agriculture manufacturing                   52577.000000  8.223900e+04
Airline                                     48169.333333  1.058317e+05
Apparel                                     46710.000000  7.910000e+04
Automotive                                 156735.000000  1.670000e+05
Automotive and Energy                       81462.000000  1.278550e+05
Automotive industry                        158057.000000  1.730000e+05
Beverage                                    86859.000000  3.150000e+05
Chemical industry                           56902.000000  3.780000e+04
Conglomerate                               141614.750000  2.244250e+05
Consumer products Manufacturing             80187.000000  1.060000e+05
Electronics industry                       394328.000000  1.640000e+05
Financial                                   53537.500000  5.104550e+04
Financial services                         154792.000000  2.937230e+05
Financials                                  84296.545455  8.955273e+04
Food Processing                             50238.000000  8.841250e+04
Food Service                                68636.000000  7.051000e+04
Food industry                               84394.000000  3.209050e+04
Health                                     276711.000000  4.850000e+04
Health Insurance                           136693.000000  6.866550e+04
Healthcare                                 198228.000000  1.887558e+05
Infotech                                    62344.000000  2.850000e+04
Insurance                                   53172.200000  4.011260e+04
Laboratory instruments                      44915.000000  1.300000e+05
Logistics                                   78620.000000  5.760000e+05
Machinery                                   59427.000000  1.091000e+05
Media                                       82722.000000  1.958000e+05
Petroleum industry                         152122.500000  1.834700e+04
Petroleum industry and Logistics            59043.000000  5.214000e+03
Pharmaceutical industry                    104294.142857  9.885714e+04
Retail                                     157890.900000  4.830850e+05
Retail and Cloud Computing                 513983.000000  1.540000e+06
Technology                                 116347.875000  1.425602e+05
Telecom Hardware Manufacturing              51557.000000  8.330000e+04
Telecommunications                         104094.666667  1.349333e+05
Transportation                              96925.000000  4.614745e+05

In [113]:
# Most common aggregate functions .count()
#df.groupby('Industry').count()
#df.groupby('Industry').min('Revenue (USD millions)')
#df.groupby('Industry').max('Revenue (USD millions)')
#df.groupby('Industry').sum('Revenue (USD millions)')

In [121]:
# Aggregation function .agg() to have multiple aggs in the same groupby statement

df.groupby('Industry').agg({'Revenue (USD millions)':['mean','max','min','sum'], 'Employees':['mean','max','min','sum'] })

                                 Revenue (USD millions)                  \
                                                   mean     max     min
Industry
Aerospace and Defense                      65984.000000   65984   65984
Aerospace and defense                      66608.000000   66608   66608
Agriculture cooperative                    47194.000000   47194   47194
Agriculture manufacturing                  52577.000000   52577   52577
Airline                                    48169.333333   50582   44955
Apparel                                    46710.000000   46710   46710
Automotive                                156735.000000  156735  156735
Automotive and Energy                      81462.000000   81462   81462
Automotive industry                       158057.000000  158057  158057
Beverage                                   86859.000000   86859   86859
Chemical industry                          56902.000000   56902   56902
Conglomerate                              141614.750000  302089   67074
Consumer products Manufacturing            80187.000000   80187   80187
Electronics industry                      394328.000000  394328  394328
Financial                                  53537.500000   55625   51450
Financial services                        154792.000000  154792  154792
Financials                                 84296.545455  121596   60050
Food Processing                            50238.000000   53282   47194
Food Service                               68636.000000   68636   68636
Food industry                              84394.000000  101556   67232
Health                                    276711.000000  276711  276711
Health Insurance                          136693.000000  180516   92870
Healthcare                                198228.000000  324162   60233
Infotech                                   62344.000000   62344   62344
Insurance                                  53172.200000   58445   49611
Laboratory instruments                     44915.000000   44915   44915
Logistics                                  78620.000000   78620   78620
Machinery                                  59427.000000   59427   59427
Media                                      82722.000000   82722   82722
Petroleum industry                        152122.500000  413680   46830
Petroleum industry and Logistics           59043.000000   59043   59043
Pharmaceutical industry                   104294.142857  238587   46159
Retail                                    157890.900000  611289   46298
Retail and Cloud Computing                513983.000000  513983  513983
Technology                                116347.875000  282836   44200
Telecom Hardware Manufacturing             51557.000000   51557   51557
Telecommunications                        104094.666667  136835   54022
Transportation                             96925.000000  100338   93512

                                              Employees                    \
                                      sum          mean      max      min
Industry
Aerospace and Defense               65984  1.160000e+05   116000   116000
Aerospace and defense               66608  1.560000e+05   156000   156000
Agriculture cooperative             47194  1.001400e+04    10014    10014
Agriculture manufacturing           52577  8.223900e+04    82239    82239
Airline                            144508  1.058317e+05   129700    92795
Apparel                             46710  7.910000e+04    79100    79100
Automotive                         156735  1.670000e+05   167000   167000
Automotive and Energy               81462  1.278550e+05   127855   127855
Automotive industry                158057  1.730000e+05   173000   173000
Beverage                            86859  3.150000e+05   315000   315000
Chemical industry                   56902  3.780000e+04    37800    37800
Conglomerate                       566459  2.244250e+05   383000   160700
Consumer products Manufacturing     80187  1.060000e+05   106000   106000
Electronics industry               394328  1.640000e+05   164000   164000
Financial                          107075  5.104550e+04    77300    24791
Financial services                 154792  2.937230e+05   293723   293723
Financials                         927262  8.955273e+04   238104      305
Food Processing                    100476  8.841250e+04   142000    34825
Food Service                        68636  7.051000e+04    70510    70510
Food industry                      168788  3.209050e+04    41181    23000
Health                             276711  4.850000e+04    48500    48500
Health Insurance                   273386  6.866550e+04    70231    67100
Healthcare                        1189368  1.887558e+05   400000    46035
Infotech                            62344  2.850000e+04    28500    28500
Insurance                          265861  4.011260e+04    55063    15050
Laboratory instruments              44915  1.300000e+05   130000   130000
Logistics                           78620  5.760000e+05   576000   576000
Machinery                           59427  1.091000e+05   109100   109100
Media                               82722  1.958000e+05   195800   195800
Petroleum industry                1521225  1.834700e+04    62000     3616
Petroleum industry and Logistics    59043  5.214000e+03     5214     5214
Pharmaceutical industry            730059  9.885714e+04   262500    34300
Retail                            1578909  4.830850e+05  2100000    71100
Retail and Cloud Computing         513983  1.540000e+06  1540000  1540000
Technology                         930783  1.425602e+05   303100    51000
Telecom Hardware Manufacturing      51557  8.330000e+04    83300    83300
Telecommunications                 312284  1.349333e+05   186000   101700
Transportation                     193850  4.614745e+05   518249   404700


                                      sum
Industry
Aerospace and Defense              116000
Aerospace and defense              156000
Agriculture cooperative             10014
Agriculture manufacturing           82239
Airline                            317495
Apparel                             79100
Automotive                         167000
Automotive and Energy              127855
Automotive industry                173000
Beverage                           315000
Chemical industry                   37800
Conglomerate                       897700
Consumer products Manufacturing    106000
Electronics industry               164000
Financial                          102091
Financial services                 293723
Financials                         985080
Food Processing                    176825
Food Service                        70510
Food industry                       64181
Health                              48500
Health Insurance                   137331
Healthcare                        1132535
Infotech                            28500
Insurance                          200563
Laboratory instruments             130000
Logistics                          576000
Machinery                          109100
Media                              195800
Petroleum industry                 183470
Petroleum industry and Logistics     5214
Pharmaceutical industry            692000
Retail                            4830850
Retail and Cloud Computing        1540000
Technology                        1140482
Telecom Hardware Manufacturing      83300
Telecommunications                 404800
Transportation                     922949

In [136]:
df.groupby(df['Industry']).agg({'Revenue (USD millions)':['mean','max','min','sum'], 'Employees':['mean','max','min','sum'] })

                                 Revenue (USD millions)                  \
                                                   mean     max     min
Industry
Aerospace and Defense                      65984.000000   65984   65984
Aerospace and defense                      66608.000000   66608   66608
Agriculture cooperative                    47194.000000   47194   47194
Agriculture manufacturing                  52577.000000   52577   52577
Airline                                    48169.333333   50582   44955
Apparel                                    46710.000000   46710   46710
Automotive                                156735.000000  156735  156735
Automotive and Energy                      81462.000000   81462   81462
Automotive industry                       158057.000000  158057  158057
Beverage                                   86859.000000   86859   86859
Chemical industry                          56902.000000   56902   56902
Conglomerate                              141614.750000  302089   67074
Consumer products Manufacturing            80187.000000   80187   80187
Electronics industry                      394328.000000  394328  394328
Financial                                  53537.500000   55625   51450
Financial services                        154792.000000  154792  154792
Financials                                 84296.545455  121596   60050
Food Processing                            50238.000000   53282   47194
Food Service                               68636.000000   68636   68636
Food industry                              84394.000000  101556   67232
Health                                    276711.000000  276711  276711
Health Insurance                          136693.000000  180516   92870
Healthcare                                198228.000000  324162   60233
Infotech                                   62344.000000   62344   62344
Insurance                                  53172.200000   58445   49611
Laboratory instruments                     44915.000000   44915   44915
Logistics                                  78620.000000   78620   78620
Machinery                                  59427.000000   59427   59427
Media                                      82722.000000   82722   82722
Petroleum industry                        152122.500000  413680   46830
Petroleum industry and Logistics           59043.000000   59043   59043
Pharmaceutical industry                   104294.142857  238587   46159
Retail                                    157890.900000  611289   46298
Retail and Cloud Computing                513983.000000  513983  513983
Technology                                116347.875000  282836   44200
Telecom Hardware Manufacturing             51557.000000   51557   51557
Telecommunications                        104094.666667  136835   54022
Transportation                             96925.000000  100338   93512

                                              Employees                    \
                                      sum          mean      max      min
Industry
Aerospace and Defense               65984  1.160000e+05   116000   116000
Aerospace and defense               66608  1.560000e+05   156000   156000
Agriculture cooperative             47194  1.001400e+04    10014    10014
Agriculture manufacturing           52577  8.223900e+04    82239    82239
Airline                            144508  1.058317e+05   129700    92795
Apparel                             46710  7.910000e+04    79100    79100
Automotive                         156735  1.670000e+05   167000   167000
Automotive and Energy               81462  1.278550e+05   127855   127855
Automotive industry                158057  1.730000e+05   173000   173000
Beverage                            86859  3.150000e+05   315000   315000
Chemical industry                   56902  3.780000e+04    37800    37800
Conglomerate                       566459  2.244250e+05   383000   160700
Consumer products Manufacturing     80187  1.060000e+05   106000   106000
Electronics industry               394328  1.640000e+05   164000   164000
Financial                          107075  5.104550e+04    77300    24791
Financial services                 154792  2.937230e+05   293723   293723
Financials                         927262  8.955273e+04   238104      305
Food Processing                    100476  8.841250e+04   142000    34825
Food Service                        68636  7.051000e+04    70510    70510
Food industry                      168788  3.209050e+04    41181    23000
Health                             276711  4.850000e+04    48500    48500
Health Insurance                   273386  6.866550e+04    70231    67100
Healthcare                        1189368  1.887558e+05   400000    46035
Infotech                            62344  2.850000e+04    28500    28500
Insurance                          265861  4.011260e+04    55063    15050
Laboratory instruments              44915  1.300000e+05   130000   130000
Logistics                           78620  5.760000e+05   576000   576000
Machinery                           59427  1.091000e+05   109100   109100
Media                               82722  1.958000e+05   195800   195800
Petroleum industry                1521225  1.834700e+04    62000     3616
Petroleum industry and Logistics    59043  5.214000e+03     5214     5214
Pharmaceutical industry            730059  9.885714e+04   262500    34300
Retail                            1578909  4.830850e+05  2100000    71100
Retail and Cloud Computing         513983  1.540000e+06  1540000  1540000
Technology                         930783  1.425602e+05   303100    51000
Telecom Hardware Manufacturing      51557  8.330000e+04    83300    83300
Telecommunications                 312284  1.349333e+05   186000   101700
Transportation                     193850  4.614745e+05   518249   404700


                                      sum
Industry
Aerospace and Defense              116000
Aerospace and defense              156000
Agriculture cooperative             10014
Agriculture manufacturing           82239
Airline                            317495
Apparel                             79100
Automotive                         167000
Automotive and Energy              127855
Automotive industry                173000
Beverage                           315000
Chemical industry                   37800
Conglomerate                       897700
Consumer products Manufacturing    106000
Electronics industry               164000
Financial                          102091
Financial services                 293723
Financials                         985080
Food Processing                    176825
Food Service                        70510
Food industry                       64181
Health                              48500
Health Insurance                   137331
Healthcare                        1132535
Infotech                            28500
Insurance                          200563
Laboratory instruments             130000
Logistics                          576000
Machinery                          109100
Media                              195800
Petroleum industry                 183470
Petroleum industry and Logistics     5214
Pharmaceutical industry            692000
Retail                            4830850
Retail and Cloud Computing        1540000
Technology                        1140482
Telecom Hardware Manufacturing      83300
Telecommunications                 404800
Transportation                     922949

In [147]:
# Groupby multiple columns
df.groupby(['Industry', 'Headquarters']).describe()

                                                                            Revenue (USD millions)  \
                                                                                             count
Industry                         Headquarters
Aerospace and Defense            Bethesda, Maryland                                            1.0
Aerospace and defense            Chicago, Illinois                                             1.0
Agriculture cooperative          Inver Grove Heights, Minnesota                                1.0
Agriculture manufacturing        Moline, Illinois                                              1.0
Airline                          Atlanta, Georgia                                              1.0
                                 Chicago, Illinois                                             1.0
                                 Fort Worth, Texas                                             1.0
Apparel                          Beaverton, Oregon                                             1.0
Automotive                       Detroit, Michigan                                             1.0
Automotive and Energy            Austin, Texas                                                 1.0
Automotive industry              Dearborn, Michigan                                            1.0
Beverage                         Purchase, New York                                            1.0
Chemical industry                Midland, Michigan                                             1.0
Conglomerate                     Arlington County, Virginia                                    1.0
                                 Boston, Massachusetts                                         1.0
                                 Dallas, Texas                                                 1.0
                                 Omaha, Nebraska                                               1.0
Consumer products Manufacturing  Cincinnati, Ohio                                              1.0
Electronics industry             Cupertino, California                                         1.0
Financial                        Columbus, Ohio                                                1.0
                                 New York City, New York                                       1.0
Financial services               New York City, New York                                       1.0
Financials                       Bloomington, Illinois                                         1.0
                                 Charlotte, North Carolina                                     1.0
                                 McLean, Virginia                                              1.0
                                 New York City, New York                                       5.0
                                 Newark, New Jersey                                            1.0
                                 San Francisco, California                                     1.0
                                 Washington, D.C.                                              1.0
Food Processing                  Richmond, Virginia                                            1.0
                                 Springdale, Arkansas                                          1.0
Food Service                     Houston, Texas                                                1.0
Food industry                    Chicago, Illinois                                             1.0
                                 White Plains, New York                                        1.0
Health                           Irving, Texas                                                 1.0
Health Insurance                 Bloomfield, Connecticut                                       1.0
                                 Louisville, Kentucky                                          1.0
Healthcare                       Dublin, Ohio                                                  1.0
                                 Indianapolis, Indiana                                         1.0
                                 Minnetonka, Minnesota                                         1.0
                                 Nashville, Tennessee                                          1.0
                                 St. Louis, Missouri                                           1.0
                                 Woonsocket, Rhode Island                                      1.0
Infotech                         Clearwater, Florida                                           1.0
Insurance                        Boston, Massachusetts                                         1.0
                                 Mayfield Village, Ohio                                        1.0
                                 New York City, New York                                       2.0
                                 Northfield Township, Cook County, Illinois                    1.0
Laboratory instruments           Waltham, Massachusetts                                        1.0
Logistics                        Washington, D.C.                                              1.0
Machinery                        Deerfield, Illinois                                           1.0
Media                            Burbank, California                                           1.0
Petroleum industry               Dallas, Texas                                                 1.0
                                 Findlay, Ohio                                                 1.0
                                 Houston, Texas                                                4.0
                                 Parsippany–Troy Hills, New Jersey                             1.0
                                 San Antonio, Texas                                            1.0
                                 San Ramon, California                                         1.0
                                 Spring, Texas                                                 1.0
Petroleum industry and Logistics Miami, Florida                                                1.0
Pharmaceutical industry          Chesterbrook, Pennsylvania                                    1.0
                                 Deerfield, Illinois                                           1.0
                                 Kenilworth, New Jersey                                        1.0
                                 Lake Bluff, Illinois                                          1.0
                                 New Brunswick, New Jersey                                     1.0
                                 New York City, New York                                       2.0
Retail                           Atlanta, Georgia                                              1.0
                                 Bentonville, Arkansas                                         1.0
                                 Boise, Idaho                                                  1.0
                                 Cincinnati, Ohio                                              1.0
                                 Framingham, Massachusetts                                     1.0
                                 Issaquah, Washington                                          1.0
                                 Lakeland, Florida                                             1.0
                                 Minneapolis, Minnesota                                        1.0
                                 Mooresville, North Carolina                                   1.0
                                 Richfield, Minnesota                                          1.0
Retail and Cloud Computing       Seattle, Washington                                           1.0
Technology                       Armonk, New York                                              1.0
                                 Menlo Park, California                                        1.0
                                 Mountain View, California                                     1.0
                                 Palo Alto, California                                         1.0
                                 Redmond, Washington                                           1.0
                                 Round Rock, Texas                                             1.0
                                 San Diego, California                                         1.0
                                 Santa Clara, California                                       1.0
Telecom Hardware Manufacturing   San Jose, California                                          1.0
Telecommunications               New York City, New York                                       1.0
                                 Philadelphia, Pennsylvania                                    1.0
                                 Stamford, Connecticut                                         1.0
Transportation                   Atlanta, Georgia                                              1.0
                                 Memphis, Tennessee                                            1.0

                                                                                       \
                                                                                 mean
Industry                         Headquarters
Aerospace and Defense            Bethesda, Maryland                           65984.0
Aerospace and defense            Chicago, Illinois                            66608.0
Agriculture cooperative          Inver Grove Heights, Minnesota               47194.0
Agriculture manufacturing        Moline, Illinois                             52577.0
Airline                          Atlanta, Georgia                             50582.0
                                 Chicago, Illinois                            44955.0
                                 Fort Worth, Texas                            48971.0
Apparel                          Beaverton, Oregon                            46710.0
Automotive                       Detroit, Michigan                           156735.0
Automotive and Energy            Austin, Texas                                81462.0
Automotive industry              Dearborn, Michigan                          158057.0
Beverage                         Purchase, New York                           86859.0
Chemical industry                Midland, Michigan                            56902.0
Conglomerate                     Arlington County, Virginia                   67074.0
                                 Boston, Massachusetts                        76555.0
                                 Dallas, Texas                               120741.0
                                 Omaha, Nebraska                             302089.0
Consumer products Manufacturing  Cincinnati, Ohio                             80187.0
Electronics industry             Cupertino, California                       394328.0
Financial                        Columbus, Ohio                               51450.0
                                 New York City, New York                      55625.0
Financial services               New York City, New York                     154792.0
Financials                       Bloomington, Illinois                        89328.0
                                 Charlotte, North Carolina                   115053.0
                                 McLean, Virginia                             86717.0
                                 New York City, New York                      74331.8
                                 Newark, New Jersey                           60050.0
                                 San Francisco, California                    82859.0
                                 Washington, D.C.                            121596.0
Food Processing                  Richmond, Virginia                           47194.0
                                 Springdale, Arkansas                         53282.0
Food Service                     Houston, Texas                               68636.0
Food industry                    Chicago, Illinois                           101556.0
                                 White Plains, New York                       67232.0
Health                           Irving, Texas                               276711.0
Health Insurance                 Bloomfield, Connecticut                     180516.0
                                 Louisville, Kentucky                         92870.0
Healthcare                       Dublin, Ohio                                181364.0
                                 Indianapolis, Indiana                       156595.0
                                 Minnetonka, Minnesota                       324162.0
                                 Nashville, Tennessee                         60233.0
                                 St. Louis, Missouri                         144547.0
                                 Woonsocket, Rhode Island                    322467.0
Infotech                         Clearwater, Florida                          62344.0
Insurance                        Boston, Massachusetts                        49956.0
                                 Mayfield Village, Ohio                       49611.0
                                 New York City, New York                      57441.0
                                 Northfield Township, Cook County, Illinois   51412.0
Laboratory instruments           Waltham, Massachusetts                       44915.0
Logistics                        Washington, D.C.                             78620.0
Machinery                        Deerfield, Illinois                          59427.0
Media                            Burbank, California                          82722.0
Petroleum industry               Dallas, Texas                                89876.0
                                 Findlay, Ohio                               180012.0
                                 Houston, Texas                               93346.5
                                 Parsippany–Troy Hills, New Jersey            46830.0
                                 San Antonio, Texas                          171189.0
                                 San Ramon, California                       246252.0
                                 Spring, Texas                               413680.0
Petroleum industry and Logistics Miami, Florida                               59043.0
Pharmaceutical industry          Chesterbrook, Pennsylvania                  238587.0
                                 Deerfield, Illinois                         132703.0
                                 Kenilworth, New Jersey                       59283.0
                                 Lake Bluff, Illinois                         58054.0
                                 New Brunswick, New Jersey                    94943.0
                                 New York City, New York                      73244.5
Retail                           Atlanta, Georgia                            157403.0
                                 Bentonville, Arkansas                       611289.0
                                 Boise, Idaho                                 77650.0
                                 Cincinnati, Ohio                            148258.0
                                 Framingham, Massachusetts                    49936.0
                                 Issaquah, Washington                        226954.0
                                 Lakeland, Florida                            54942.0
                                 Minneapolis, Minnesota                      109120.0
                                 Mooresville, North Carolina                  97059.0
                                 Richfield, Minnesota                         46298.0
Retail and Cloud Computing       Seattle, Washington                         513983.0
Technology                       Armonk, New York                             60530.0
                                 Menlo Park, California                      116609.0
                                 Mountain View, California                   282836.0
                                 Palo Alto, California                        62983.0
                                 Redmond, Washington                         198270.0
                                 Round Rock, Texas                           102301.0
                                 San Diego, California                        44200.0
                                 Santa Clara, California                      63054.0
Telecom Hardware Manufacturing   San Jose, California                         51557.0
Telecommunications               New York City, New York                     136835.0
                                 Philadelphia, Pennsylvania                  121427.0
                                 Stamford, Connecticut                        54022.0
Transportation                   Atlanta, Georgia                            100338.0
                                 Memphis, Tennessee                           93512.0

                                                                                           \
                                                                                      std
Industry                         Headquarters
Aerospace and Defense            Bethesda, Maryland                                   NaN
Aerospace and defense            Chicago, Illinois                                    NaN
Agriculture cooperative          Inver Grove Heights, Minnesota                       NaN
Agriculture manufacturing        Moline, Illinois                                     NaN
Airline                          Atlanta, Georgia                                     NaN
                                 Chicago, Illinois                                    NaN
                                 Fort Worth, Texas                                    NaN
Apparel                          Beaverton, Oregon                                    NaN
Automotive                       Detroit, Michigan                                    NaN
Automotive and Energy            Austin, Texas                                        NaN
Automotive industry              Dearborn, Michigan                                   NaN
Beverage                         Purchase, New York                                   NaN
Chemical industry                Midland, Michigan                                    NaN
Conglomerate                     Arlington County, Virginia                           NaN
                                 Boston, Massachusetts                                NaN
                                 Dallas, Texas                                        NaN
                                 Omaha, Nebraska                                      NaN
Consumer products Manufacturing  Cincinnati, Ohio                                     NaN
Electronics industry             Cupertino, California                                NaN
Financial                        Columbus, Ohio                                       NaN
                                 New York City, New York                              NaN
Financial services               New York City, New York                              NaN
Financials                       Bloomington, Illinois                                NaN
                                 Charlotte, North Carolina                            NaN
                                 McLean, Virginia                                     NaN
                                 New York City, New York                     15049.260321
                                 Newark, New Jersey                                   NaN