# MERGE JOIN AND CONCATENATE

In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv(r'C:\Users\Gerardo\Downloads\NHL_1992_standings.csv')
df2 = pd.read_csv(r'C:\Users\Gerardo\Documents\Python\Python Web Scraping\NHL 90s\NHL_1993_standings.csv')

In [4]:
df1

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Pittsburgh Penguins,1992,56,21,NaN,0.667,367,268,99
1,Boston Bruins,1992,51,26,NaN,0.607,332,268,64
2,Montreal Canadiens,1992,48,30,NaN,0.571,326,280,46
3,Chicago Blackhawks,1992,47,25,NaN,0.560,279,230,49
4,Detroit Red Wings,1992,47,28,NaN,0.560,369,280,89
5,Quebec Nordiques,1992,47,27,NaN,0.560,351,300,51
6,Vancouver Canucks,1992,46,29,NaN,0.548,346,278,68
7,Toronto Maple Leafs,1992,44,29,NaN,0.524,288,241,47
8,Calgary Flames,1992,43,30,NaN,0.512,322,282,40
9,Washington Capitals,1992,43,34,NaN,0.512,325,286,39
10,New York Islanders,1992,40,37,NaN,0.476,335,297,38
11,Winnipeg Jets,1992,40,37,NaN,0.476,322,320,2
12,New Jersey Devils,1992,40,37,NaN,0.476,308,299,9
13,Los Angeles Kings,1992,39,35,NaN,0.464,338,340,-2
14,Buffalo Sabres,1992,38,36,NaN,0.452,335,297,38
15,St. Louis Blues,1992,37,36,NaN,0.440,282,278,4
16,Philadelphia Flyers,1992,36,37,NaN,0.429,319,319,0
17,Minnesota North Stars,1992,36,38,NaN,0.429,272,293,-21
18,New York Rangers,1992,34,39,NaN,0.405,304,308,-4
19,Hartford Whalers,1992,26,52,NaN,0.310,284,369,-85
20,Edmonton Oilers,1992,26,50,NaN,0.310,242,337,-95
21,Tampa Bay Lightning,1992,23,54,NaN,0.274,245,332,-87
22,San Jose Sharks,1992,11,71,NaN,0.131,218,414,-196
23,Ottawa Senators,1992,10,70,NaN,0.119,202,395,-193

In [5]:
df2

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,New York Rangers,1993,52,24,NaN,0.619,299,231,68
1,New Jersey Devils,1993,47,25,NaN,0.560,306,220,86
2,Detroit Red Wings,1993,46,30,NaN,0.548,356,275,81
3,Pittsburgh Penguins,1993,44,27,NaN,0.524,299,285,14
4,Toronto Maple Leafs,1993,43,29,NaN,0.512,280,243,37
5,Buffalo Sabres,1993,43,32,NaN,0.512,282,218,64
6,Dallas Stars,1993,42,29,NaN,0.500,286,265,21
7,Calgary Flames,1993,42,29,NaN,0.500,302,256,46
8,Boston Bruins,1993,42,29,NaN,0.500,289,252,37
9,Vancouver Canucks,1993,41,40,NaN,0.488,279,276,3
10,Montreal Canadiens,1993,41,29,NaN,0.488,283,248,35
11,St. Louis Blues,1993,40,33,NaN,0.476,270,283,-13
12,Chicago Blackhawks,1993,39,36,NaN,0.464,254,240,14
13,Washington Capitals,1993,39,35,NaN,0.464,277,263,14
14,New York Islanders,1993,36,36,NaN,0.429,282,264,18
15,Philadelphia Flyers,1993,35,39,NaN,0.417,294,314,-20
16,Quebec Nordiques,1993,34,42,NaN,0.405,277,292,-15
17,San Jose Sharks,1993,33,35,NaN,0.393,252,265,-13
18,Mighty Ducks of Anaheim,1993,33,46,NaN,0.393,229,251,-22
19,Florida Panthers,1993,33,34,NaN,0.393,233,233,0
20,Tampa Bay Lightning,1993,30,43,NaN,0.357,224,251,-27
21,Los Angeles Kings,1993,27,45,NaN,0.321,294,322,-28
22,Hartford Whalers,1993,27,48,NaN,0.321,227,288,-61
23,Edmonton Oilers,1993,25,45,NaN,0.298,261,305,-44
24,Winnipeg Jets,1993,24,51,NaN,0.286,245,344,-99
25,Ottawa Senators,1993,14,61,NaN,0.167,201,397,-196

In [7]:
df1.info()
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Team Name           24 non-null     object
 1   Year                24 non-null     int64
 2   Wins                24 non-null     int64
 3   Losses              24 non-null     int64
 4   OT Losses           0 non-null      float64
 5   Win %               24 non-null     float64
 6   Goals For (GF)      24 non-null     int64
 7   Goals Against (GA)  24 non-null     int64
 8   + / -               24 non-null     int64
dtypes: float64(2), int64(6), object(1)
memory usage: 1.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Team Name           26 non-null     object
 1   Year                26 non-null     int64
 2   Wins                26 non-null     int64
 3   Losses              26 non-null     int64
 4   OT Losses           0 non-null      float64
 5   Win %               26 non-null     float64
 6   Goals For (GF)      26 non-null     int64
 7   Goals Against (GA)  26 non-null     int64
 8   + / -               26 non-null     int64
dtypes: float64(2), int64(6), object(1)
memory usage: 2.0+ KB

In [10]:
# Merge the most important kind of join (like SQL joins) df1.merge(df2)
df1.merge(df2, on='Team Name')

,Team Name,Year_x,Wins_x,Losses_x,OT Losses_x,Win %_x,Goals For (GF)_x,Goals Against (GA)_x,+ / -_x,Year_y,Wins_y,Losses_y,OT Losses_y,Win %_y,Goals For (GF)_y,Goals Against (GA)_y,+ / -_y
0,Pittsburgh Penguins,1992,56,21,NaN,0.667,367,268,99,1993,44,27,NaN,0.524,299,285,14
1,Boston Bruins,1992,51,26,NaN,0.607,332,268,64,1993,42,29,NaN,0.500,289,252,37
2,Montreal Canadiens,1992,48,30,NaN,0.571,326,280,46,1993,41,29,NaN,0.488,283,248,35
3,Chicago Blackhawks,1992,47,25,NaN,0.560,279,230,49,1993,39,36,NaN,0.464,254,240,14
4,Detroit Red Wings,1992,47,28,NaN,0.560,369,280,89,1993,46,30,NaN,0.548,356,275,81
5,Quebec Nordiques,1992,47,27,NaN,0.560,351,300,51,1993,34,42,NaN,0.405,277,292,-15
6,Vancouver Canucks,1992,46,29,NaN,0.548,346,278,68,1993,41,40,NaN,0.488,279,276,3
7,Toronto Maple Leafs,1992,44,29,NaN,0.524,288,241,47,1993,43,29,NaN,0.512,280,243,37
8,Calgary Flames,1992,43,30,NaN,0.512,322,282,40,1993,42,29,NaN,0.500,302,256,46
9,Washington Capitals,1992,43,34,NaN,0.512,325,286,39,1993,39,35,NaN,0.464,277,263,14
10,New York Islanders,1992,40,37,NaN,0.476,335,297,38,1993,36,36,NaN,0.429,282,264,18
11,Winnipeg Jets,1992,40,37,NaN,0.476,322,320,2,1993,24,51,NaN,0.286,245,344,-99
12,New Jersey Devils,1992,40,37,NaN,0.476,308,299,9,1993,47,25,NaN,0.560,306,220,86
13,Los Angeles Kings,1992,39,35,NaN,0.464,338,340,-2,1993,27,45,NaN,0.321,294,322,-28
14,Buffalo Sabres,1992,38,36,NaN,0.452,335,297,38,1993,43,32,NaN,0.512,282,218,64
15,St. Louis Blues,1992,37,36,NaN,0.440,282,278,4,1993,40,33,NaN,0.476,270,283,-13
16,Philadelphia Flyers,1992,36,37,NaN,0.429,319,319,0,1993,35,39,NaN,0.417,294,314,-20
17,New York Rangers,1992,34,39,NaN,0.405,304,308,-4,1993,52,24,NaN,0.619,299,231,68
18,Hartford Whalers,1992,26,52,NaN,0.310,284,369,-85,1993,27,48,NaN,0.321,227,288,-61
19,Edmonton Oilers,1992,26,50,NaN,0.310,242,337,-95,1993,25,45,NaN,0.298,261,305,-44
20,Tampa Bay Lightning,1992,23,54,NaN,0.274,245,332,-87,1993,30,43,NaN,0.357,224,251,-27
21,San Jose Sharks,1992,11,71,NaN,0.131,218,414,-196,1993,33,35,NaN,0.393,252,265,-13
22,Ottawa Senators,1992,10,70,NaN,0.119,202,395,-193,1993,14,61,NaN,0.167,201,397,-196

In [14]:
# Left/Right join with .merge() argument how = left, custom x and y values to identify each
df1.merge(df2, how = 'right', on='Team Name', suffixes = (' 1992',' 1993'))

,Team Name,Year 1992,Wins 1992,Losses 1992,OT Losses 1992,Win % 1992,Goals For (GF) 1992,Goals Against (GA) 1992,+ / - 1992,Year 1993,Wins 1993,Losses 1993,OT Losses 1993,Win % 1993,Goals For (GF) 1993,Goals Against (GA) 1993,+ / - 1993
0,New York Rangers,1992.0,34.0,39.0,NaN,0.405,304.0,308.0,-4.0,1993,52,24,NaN,0.619,299,231,68
1,New Jersey Devils,1992.0,40.0,37.0,NaN,0.476,308.0,299.0,9.0,1993,47,25,NaN,0.560,306,220,86
2,Detroit Red Wings,1992.0,47.0,28.0,NaN,0.560,369.0,280.0,89.0,1993,46,30,NaN,0.548,356,275,81
3,Pittsburgh Penguins,1992.0,56.0,21.0,NaN,0.667,367.0,268.0,99.0,1993,44,27,NaN,0.524,299,285,14
4,Toronto Maple Leafs,1992.0,44.0,29.0,NaN,0.524,288.0,241.0,47.0,1993,43,29,NaN,0.512,280,243,37
5,Buffalo Sabres,1992.0,38.0,36.0,NaN,0.452,335.0,297.0,38.0,1993,43,32,NaN,0.512,282,218,64
6,Dallas Stars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993,42,29,NaN,0.500,286,265,21
7,Calgary Flames,1992.0,43.0,30.0,NaN,0.512,322.0,282.0,40.0,1993,42,29,NaN,0.500,302,256,46
8,Boston Bruins,1992.0,51.0,26.0,NaN,0.607,332.0,268.0,64.0,1993,42,29,NaN,0.500,289,252,37
9,Vancouver Canucks,1992.0,46.0,29.0,NaN,0.548,346.0,278.0,68.0,1993,41,40,NaN,0.488,279,276,3
10,Montreal Canadiens,1992.0,48.0,30.0,NaN,0.571,326.0,280.0,46.0,1993,41,29,NaN,0.488,283,248,35
11,St. Louis Blues,1992.0,37.0,36.0,NaN,0.440,282.0,278.0,4.0,1993,40,33,NaN,0.476,270,283,-13
12,Chicago Blackhawks,1992.0,47.0,25.0,NaN,0.560,279.0,230.0,49.0,1993,39,36,NaN,0.464,254,240,14
13,Washington Capitals,1992.0,43.0,34.0,NaN,0.512,325.0,286.0,39.0,1993,39,35,NaN,0.464,277,263,14
14,New York Islanders,1992.0,40.0,37.0,NaN,0.476,335.0,297.0,38.0,1993,36,36,NaN,0.429,282,264,18
15,Philadelphia Flyers,1992.0,36.0,37.0,NaN,0.429,319.0,319.0,0.0,1993,35,39,NaN,0.417,294,314,-20
16,Quebec Nordiques,1992.0,47.0,27.0,NaN,0.560,351.0,300.0,51.0,1993,34,42,NaN,0.405,277,292,-15
17,San Jose Sharks,1992.0,11.0,71.0,NaN,0.131,218.0,414.0,-196.0,1993,33,35,NaN,0.393,252,265,-13
18,Mighty Ducks of Anaheim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993,33,46,NaN,0.393,229,251,-22
19,Florida Panthers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993,33,34,NaN,0.393,233,233,0
20,Tampa Bay Lightning,1992.0,23.0,54.0,NaN,0.274,245.0,332.0,-87.0,1993,30,43,NaN,0.357,224,251,-27
21,Los Angeles Kings,1992.0,39.0,35.0,NaN,0.464,338.0,340.0,-2.0,1993,27,45,NaN,0.321,294,322,-28
22,Hartford Whalers,1992.0,26.0,52.0,NaN,0.310,284.0,369.0,-85.0,1993,27,48,NaN,0.321,227,288,-61
23,Edmonton Oilers,1992.0,26.0,50.0,NaN,0.310,242.0,337.0,-95.0,1993,25,45,NaN,0.298,261,305,-44
24,Winnipeg Jets,1992.0,40.0,37.0,NaN,0.476,322.0,320.0,2.0,1993,24,51,NaN,0.286,245,344,-99
25,Ottawa Senators,1992.0,10.0,70.0,NaN,0.119,202.0,395.0,-193.0,1993,14,61,NaN,0.167,201,397,-196

In [15]:
# Outer Join with merge() how = 'outer' 
df1.merge(df2, how='outer',on='Team Name')

,Team Name,Year_x,Wins_x,Losses_x,OT Losses_x,Win %_x,Goals For (GF)_x,Goals Against (GA)_x,+ / -_x,Year_y,Wins_y,Losses_y,OT Losses_y,Win %_y,Goals For (GF)_y,Goals Against (GA)_y,+ / -_y
0,Pittsburgh Penguins,1992.0,56.0,21.0,NaN,0.667,367.0,268.0,99.0,1993.0,44.0,27.0,NaN,0.524,299.0,285.0,14.0
1,Boston Bruins,1992.0,51.0,26.0,NaN,0.607,332.0,268.0,64.0,1993.0,42.0,29.0,NaN,0.500,289.0,252.0,37.0
2,Montreal Canadiens,1992.0,48.0,30.0,NaN,0.571,326.0,280.0,46.0,1993.0,41.0,29.0,NaN,0.488,283.0,248.0,35.0
3,Chicago Blackhawks,1992.0,47.0,25.0,NaN,0.560,279.0,230.0,49.0,1993.0,39.0,36.0,NaN,0.464,254.0,240.0,14.0
4,Detroit Red Wings,1992.0,47.0,28.0,NaN,0.560,369.0,280.0,89.0,1993.0,46.0,30.0,NaN,0.548,356.0,275.0,81.0
5,Quebec Nordiques,1992.0,47.0,27.0,NaN,0.560,351.0,300.0,51.0,1993.0,34.0,42.0,NaN,0.405,277.0,292.0,-15.0
6,Vancouver Canucks,1992.0,46.0,29.0,NaN,0.548,346.0,278.0,68.0,1993.0,41.0,40.0,NaN,0.488,279.0,276.0,3.0
7,Toronto Maple Leafs,1992.0,44.0,29.0,NaN,0.524,288.0,241.0,47.0,1993.0,43.0,29.0,NaN,0.512,280.0,243.0,37.0
8,Calgary Flames,1992.0,43.0,30.0,NaN,0.512,322.0,282.0,40.0,1993.0,42.0,29.0,NaN,0.500,302.0,256.0,46.0
9,Washington Capitals,1992.0,43.0,34.0,NaN,0.512,325.0,286.0,39.0,1993.0,39.0,35.0,NaN,0.464,277.0,263.0,14.0
10,New York Islanders,1992.0,40.0,37.0,NaN,0.476,335.0,297.0,38.0,1993.0,36.0,36.0,NaN,0.429,282.0,264.0,18.0
11,Winnipeg Jets,1992.0,40.0,37.0,NaN,0.476,322.0,320.0,2.0,1993.0,24.0,51.0,NaN,0.286,245.0,344.0,-99.0
12,New Jersey Devils,1992.0,40.0,37.0,NaN,0.476,308.0,299.0,9.0,1993.0,47.0,25.0,NaN,0.560,306.0,220.0,86.0
13,Los Angeles Kings,1992.0,39.0,35.0,NaN,0.464,338.0,340.0,-2.0,1993.0,27.0,45.0,NaN,0.321,294.0,322.0,-28.0
14,Buffalo Sabres,1992.0,38.0,36.0,NaN,0.452,335.0,297.0,38.0,1993.0,43.0,32.0,NaN,0.512,282.0,218.0,64.0
15,St. Louis Blues,1992.0,37.0,36.0,NaN,0.440,282.0,278.0,4.0,1993.0,40.0,33.0,NaN,0.476,270.0,283.0,-13.0
16,Philadelphia Flyers,1992.0,36.0,37.0,NaN,0.429,319.0,319.0,0.0,1993.0,35.0,39.0,NaN,0.417,294.0,314.0,-20.0
17,Minnesota North Stars,1992.0,36.0,38.0,NaN,0.429,272.0,293.0,-21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,New York Rangers,1992.0,34.0,39.0,NaN,0.405,304.0,308.0,-4.0,1993.0,52.0,24.0,NaN,0.619,299.0,231.0,68.0
19,Hartford Whalers,1992.0,26.0,52.0,NaN,0.310,284.0,369.0,-85.0,1993.0,27.0,48.0,NaN,0.321,227.0,288.0,-61.0
20,Edmonton Oilers,1992.0,26.0,50.0,NaN,0.310,242.0,337.0,-95.0,1993.0,25.0,45.0,NaN,0.298,261.0,305.0,-44.0
21,Tampa Bay Lightning,1992.0,23.0,54.0,NaN,0.274,245.0,332.0,-87.0,1993.0,30.0,43.0,NaN,0.357,224.0,251.0,-27.0
22,San Jose Sharks,1992.0,11.0,71.0,NaN,0.131,218.0,414.0,-196.0,1993.0,33.0,35.0,NaN,0.393,252.0,265.0,-13.0
23,Ottawa Senators,1992.0,10.0,70.0,NaN,0.119,202.0,395.0,-193.0,1993.0,14.0,61.0,NaN,0.167,201.0,397.0,-196.0
24,Dallas Stars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993.0,42.0,29.0,NaN,0.500,286.0,265.0,21.0
25,Mighty Ducks of Anaheim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993.0,33.0,46.0,NaN,0.393,229.0,251.0,-22.0
26,Florida Panthers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993.0,33.0,34.0,NaN,0.393,233.0,233.0,0.0

In [23]:
# Join function in pandas they work with indexes so have to be specified
df3 = df1.set_index('Team Name').join(df2.set_index('Team Name'), lsuffix = ' 1992', rsuffix = ' 1993', how = 'outer')
df3

,Year 1992,Wins 1992,Losses 1992,OT Losses 1992,Win % 1992,Goals For (GF) 1992,Goals Against (GA) 1992,+ / - 1992,Year 1993,Wins 1993,Losses 1993,OT Losses 1993,Win % 1993,Goals For (GF) 1993,Goals Against (GA) 1993,+ / - 1993
Team Name,,,,,,,,,,,,,,,,
Boston Bruins,1992.0,51.0,26.0,NaN,0.607,332.0,268.0,64.0,1993.0,42.0,29.0,NaN,0.500,289.0,252.0,37.0
Buffalo Sabres,1992.0,38.0,36.0,NaN,0.452,335.0,297.0,38.0,1993.0,43.0,32.0,NaN,0.512,282.0,218.0,64.0
Calgary Flames,1992.0,43.0,30.0,NaN,0.512,322.0,282.0,40.0,1993.0,42.0,29.0,NaN,0.500,302.0,256.0,46.0
Chicago Blackhawks,1992.0,47.0,25.0,NaN,0.560,279.0,230.0,49.0,1993.0,39.0,36.0,NaN,0.464,254.0,240.0,14.0
Dallas Stars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993.0,42.0,29.0,NaN,0.500,286.0,265.0,21.0
Detroit Red Wings,1992.0,47.0,28.0,NaN,0.560,369.0,280.0,89.0,1993.0,46.0,30.0,NaN,0.548,356.0,275.0,81.0
Edmonton Oilers,1992.0,26.0,50.0,NaN,0.310,242.0,337.0,-95.0,1993.0,25.0,45.0,NaN,0.298,261.0,305.0,-44.0
Florida Panthers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993.0,33.0,34.0,NaN,0.393,233.0,233.0,0.0
Hartford Whalers,1992.0,26.0,52.0,NaN,0.310,284.0,369.0,-85.0,1993.0,27.0,48.0,NaN,0.321,227.0,288.0,-61.0
Los Angeles Kings,1992.0,39.0,35.0,NaN,0.464,338.0,340.0,-2.0,1993.0,27.0,45.0,NaN,0.321,294.0,322.0,-28.0
Mighty Ducks of Anaheim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993.0,33.0,46.0,NaN,0.393,229.0,251.0,-22.0
Minnesota North Stars,1992.0,36.0,38.0,NaN,0.429,272.0,293.0,-21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Montreal Canadiens,1992.0,48.0,30.0,NaN,0.571,326.0,280.0,46.0,1993.0,41.0,29.0,NaN,0.488,283.0,248.0,35.0
New Jersey Devils,1992.0,40.0,37.0,NaN,0.476,308.0,299.0,9.0,1993.0,47.0,25.0,NaN,0.560,306.0,220.0,86.0
New York Islanders,1992.0,40.0,37.0,NaN,0.476,335.0,297.0,38.0,1993.0,36.0,36.0,NaN,0.429,282.0,264.0,18.0
New York Rangers,1992.0,34.0,39.0,NaN,0.405,304.0,308.0,-4.0,1993.0,52.0,24.0,NaN,0.619,299.0,231.0,68.0
Ottawa Senators,1992.0,10.0,70.0,NaN,0.119,202.0,395.0,-193.0,1993.0,14.0,61.0,NaN,0.167,201.0,397.0,-196.0
Philadelphia Flyers,1992.0,36.0,37.0,NaN,0.429,319.0,319.0,0.0,1993.0,35.0,39.0,NaN,0.417,294.0,314.0,-20.0
Pittsburgh Penguins,1992.0,56.0,21.0,NaN,0.667,367.0,268.0,99.0,1993.0,44.0,27.0,NaN,0.524,299.0,285.0,14.0
Quebec Nordiques,1992.0,47.0,27.0,NaN,0.560,351.0,300.0,51.0,1993.0,34.0,42.0,NaN,0.405,277.0,292.0,-15.0
San Jose Sharks,1992.0,11.0,71.0,NaN,0.131,218.0,414.0,-196.0,1993.0,33.0,35.0,NaN,0.393,252.0,265.0,-13.0
St. Louis Blues,1992.0,37.0,36.0,NaN,0.440,282.0,278.0,4.0,1993.0,40.0,33.0,NaN,0.476,270.0,283.0,-13.0
Tampa Bay Lightning,1992.0,23.0,54.0,NaN,0.274,245.0,332.0,-87.0,1993.0,30.0,43.0,NaN,0.357,224.0,251.0,-27.0
Toronto Maple Leafs,1992.0,44.0,29.0,NaN,0.524,288.0,241.0,47.0,1993.0,43.0,29.0,NaN,0.512,280.0,243.0,37.0
Vancouver Canucks,1992.0,46.0,29.0,NaN,0.548,346.0,278.0,68.0,1993.0,41.0,40.0,NaN,0.488,279.0,276.0,3.0
Washington Capitals,1992.0,43.0,34.0,NaN,0.512,325.0,286.0,39.0,1993.0,39.0,35.0,NaN,0.464,277.0,263.0,14.0
Winnipeg Jets,1992.0,40.0,37.0,NaN,0.476,322.0,320.0,2.0,1993.0,24.0,51.0,NaN,0.286,245.0,344.0,-99.0

In [24]:
# Use of concatenate df with .concat() works like putting one data frame on top of the other rather than next to one-another
pd.concat([df1,df2])

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Pittsburgh Penguins,1992,56,21,NaN,0.667,367,268,99
1,Boston Bruins,1992,51,26,NaN,0.607,332,268,64
2,Montreal Canadiens,1992,48,30,NaN,0.571,326,280,46
3,Chicago Blackhawks,1992,47,25,NaN,0.560,279,230,49
4,Detroit Red Wings,1992,47,28,NaN,0.560,369,280,89
5,Quebec Nordiques,1992,47,27,NaN,0.560,351,300,51
6,Vancouver Canucks,1992,46,29,NaN,0.548,346,278,68
7,Toronto Maple Leafs,1992,44,29,NaN,0.524,288,241,47
8,Calgary Flames,1992,43,30,NaN,0.512,322,282,40
9,Washington Capitals,1992,43,34,NaN,0.512,325,286,39
10,New York Islanders,1992,40,37,NaN,0.476,335,297,38
11,Winnipeg Jets,1992,40,37,NaN,0.476,322,320,2
12,New Jersey Devils,1992,40,37,NaN,0.476,308,299,9
13,Los Angeles Kings,1992,39,35,NaN,0.464,338,340,-2
14,Buffalo Sabres,1992,38,36,NaN,0.452,335,297,38
15,St. Louis Blues,1992,37,36,NaN,0.440,282,278,4
16,Philadelphia Flyers,1992,36,37,NaN,0.429,319,319,0
17,Minnesota North Stars,1992,36,38,NaN,0.429,272,293,-21
18,New York Rangers,1992,34,39,NaN,0.405,304,308,-4
19,Hartford Whalers,1992,26,52,NaN,0.310,284,369,-85
20,Edmonton Oilers,1992,26,50,NaN,0.310,242,337,-95
21,Tampa Bay Lightning,1992,23,54,NaN,0.274,245,332,-87
22,San Jose Sharks,1992,11,71,NaN,0.131,218,414,-196
23,Ottawa Senators,1992,10,70,NaN,0.119,202,395,-193
0,New York Rangers,1993,52,24,NaN,0.619,299,231,68
1,New Jersey Devils,1993,47,25,NaN,0.560,306,220,86
2,Detroit Red Wings,1993,46,30,NaN,0.548,356,275,81
3,Pittsburgh Penguins,1993,44,27,NaN,0.524,299,285,14
4,Toronto Maple Leafs,1993,43,29,NaN,0.512,280,243,37
5,Buffalo Sabres,1993,43,32,NaN,0.512,282,218,64
6,Dallas Stars,1993,42,29,NaN,0.500,286,265,21
7,Calgary Flames,1993,42,29,NaN,0.500,302,256,46
8,Boston Bruins,1993,42,29,NaN,0.500,289,252,37
9,Vancouver Canucks,1993,41,40,NaN,0.488,279,276,3
10,Montreal Canadiens,1993,41,29,NaN,0.488,283,248,35
11,St. Louis Blues,1993,40,33,NaN,0.476,270,283,-13
12,Chicago Blackhawks,1993,39,36,NaN,0.464,254,240,14
13,Washington Capitals,1993,39,35,NaN,0.464,277,263,14
14,New York Islanders,1993,36,36,NaN,0.429,282,264,18
15,Philadelphia Flyers,1993,35,39,NaN,0.417,294,314,-20
16,Quebec Nordiques,1993,34,42,NaN,0.405,277,292,-15
17,San Jose Sharks,1993,33,35,NaN,0.393,252,265,-13
18,Mighty Ducks of Anaheim,1993,33,46,NaN,0.393,229,251,-22
19,Florida Panthers,1993,33,34,NaN,0.393,233,233,0
20,Tampa Bay Lightning,1993,30,43,NaN,0.357,224,251,-27
21,Los Angeles Kings,1993,27,45,NaN,0.321,294,322,-28
22,Hartford Whalers,1993,27,48,NaN,0.321,227,288,-61
23,Edmonton Oilers,1993,25,45,NaN,0.298,261,305,-44
24,Winnipeg Jets,1993,24,51,NaN,0.286,245,344,-99
25,Ottawa Senators,1993,14,61,NaN,0.167,201,397,-196

In [25]:
# Append function .append() to add new values to the df
df1.append(df2)

C:\Users\Gerardo\AppData\Local\Temp\ipykernel_8564\1958670566.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Pittsburgh Penguins,1992,56,21,NaN,0.667,367,268,99
1,Boston Bruins,1992,51,26,NaN,0.607,332,268,64
2,Montreal Canadiens,1992,48,30,NaN,0.571,326,280,46
3,Chicago Blackhawks,1992,47,25,NaN,0.560,279,230,49
4,Detroit Red Wings,1992,47,28,NaN,0.560,369,280,89
5,Quebec Nordiques,1992,47,27,NaN,0.560,351,300,51
6,Vancouver Canucks,1992,46,29,NaN,0.548,346,278,68
7,Toronto Maple Leafs,1992,44,29,NaN,0.524,288,241,47
8,Calgary Flames,1992,43,30,NaN,0.512,322,282,40
9,Washington Capitals,1992,43,34,NaN,0.512,325,286,39
10,New York Islanders,1992,40,37,NaN,0.476,335,297,38
11,Winnipeg Jets,1992,40,37,NaN,0.476,322,320,2
12,New Jersey Devils,1992,40,37,NaN,0.476,308,299,9
13,Los Angeles Kings,1992,39,35,NaN,0.464,338,340,-2
14,Buffalo Sabres,1992,38,36,NaN,0.452,335,297,38
15,St. Louis Blues,1992,37,36,NaN,0.440,282,278,4
16,Philadelphia Flyers,1992,36,37,NaN,0.429,319,319,0
17,Minnesota North Stars,1992,36,38,NaN,0.429,272,293,-21
18,New York Rangers,1992,34,39,NaN,0.405,304,308,-4
19,Hartford Whalers,1992,26,52,NaN,0.310,284,369,-85
20,Edmonton Oilers,1992,26,50,NaN,0.310,242,337,-95
21,Tampa Bay Lightning,1992,23,54,NaN,0.274,245,332,-87
22,San Jose Sharks,1992,11,71,NaN,0.131,218,414,-196
23,Ottawa Senators,1992,10,70,NaN,0.119,202,395,-193
0,New York Rangers,1993,52,24,NaN,0.619,299,231,68
1,New Jersey Devils,1993,47,25,NaN,0.560,306,220,86
2,Detroit Red Wings,1993,46,30,NaN,0.548,356,275,81
3,Pittsburgh Penguins,1993,44,27,NaN,0.524,299,285,14
4,Toronto Maple Leafs,1993,43,29,NaN,0.512,280,243,37
5,Buffalo Sabres,1993,43,32,NaN,0.512,282,218,64
6,Dallas Stars,1993,42,29,NaN,0.500,286,265,21
7,Calgary Flames,1993,42,29,NaN,0.500,302,256,46
8,Boston Bruins,1993,42,29,NaN,0.500,289,252,37
9,Vancouver Canucks,1993,41,40,NaN,0.488,279,276,3
10,Montreal Canadiens,1993,41,29,NaN,0.488,283,248,35
11,St. Louis Blues,1993,40,33,NaN,0.476,270,283,-13
12,Chicago Blackhawks,1993,39,36,NaN,0.464,254,240,14
13,Washington Capitals,1993,39,35,NaN,0.464,277,263,14
14,New York Islanders,1993,36,36,NaN,0.429,282,264,18
15,Philadelphia Flyers,1993,35,39,NaN,0.417,294,314,-20
16,Quebec Nordiques,1993,34,42,NaN,0.405,277,292,-15
17,San Jose Sharks,1993,33,35,NaN,0.393,252,265,-13
18,Mighty Ducks of Anaheim,1993,33,46,NaN,0.393,229,251,-22
19,Florida Panthers,1993,33,34,NaN,0.393,233,233,0
20,Tampa Bay Lightning,1993,30,43,NaN,0.357,224,251,-27
21,Los Angeles Kings,1993,27,45,NaN,0.321,294,322,-28
22,Hartford Whalers,1993,27,48,NaN,0.321,227,288,-61
23,Edmonton Oilers,1993,25,45,NaN,0.298,261,305,-44
24,Winnipeg Jets,1993,24,51,NaN,0.286,245,344,-99
25,Ottawa Senators,1993,14,61,NaN,0.167,201,397,-196